### ISSUE TITLE
test_bn fails insufficient buffer on i686

### ISSUE THREAD

**Issue by cjpn** [relic-toolkit/relic#102]
I am trying to benchmark pairings using the BN_P256 elliptic curve on a NexCom vehicle computer running Voyage Linux. The computer has an i686 processor.

I compiled the code with -DARCH=X86 -DWSIZE=32 -DARITH=gmp.

Running ctest, test_bn fails:
Testing if modular exponentiation with zero power is correct...
ERROR in bn_rec_slw() at 
/opt/relic/relic-master/src/bn/relic_bn_rec.c,116: insufficient buffer 
capacity.
     CAUGHT in bn_mxp_slide() at 
/opt/relic/relic-master/src/bn/relic_bn_mxp.c,186.

I am not sure how to proceed with this? Please can you help?

**Comment by cjpn** [comment]
Hi,
Sorry for the delay this is a free time activity. Here is some further information:

Linux vanet1 4.1.6-voyage #1 SMP Fri Jun 3 10:04:48 HKT 2016 i686 GNU/Linux

4 processors with:
vendor_id	: GenuineIntel
cpu family	: 6
model		: 28
model name	: Intel(R) Atom(TM) CPU D510   @ 1.66GHz

================================================================================
cmake ../relic-master gave:

In file included from /opt/relic/relic-master/include/relic_arch.h:38:0,
                 from /opt/relic/relic-master/include/relic_util.h:38,
                 from /opt/relic/relic-master/include/relic_err.h:42,
                 from /opt/relic/relic-master/include/relic_core.h:43,
                 from /opt/relic/relic-master/src/relic_err.c:36:
/opt/relic/relic-master/include/relic_types.h:112:9: error: unknown type name '__uint128_t'
 typedef __uint128_t dbl_t;

================================================================================
cmake ../relic-master -DARCH=X86 -DWSIZE=32 -DWORD=32 ../relic-master:

make succeeded, but the tests fail. I attach the log for the tests. I stopped at test_fpx as this started and didn't finish after a long time.

[LastTest.log](https://github.com/relic-toolkit/relic/files/2617036/LastTest.log)

Thank you.

**Comment by dfaranha** [comment]
Hi,

No problem, same here!

I could not reproduce the issue in a 32-bit ARM processor, which is the closest I have. However, I just improved handling of the zero exponents, so let's see if this was solved indirectly.

**Comment by cjpn** [comment]
Hi,
I updated and rebuilt the library and test_bn no longer fails. However, ctest still fails and reports:

Total Test time (real) = 5358.34 sec  (this is not a fast processor)

The following tests FAILED:
	  8 - test_ep (Failed)
	 13 - test_pc (Failed)
	 16 - test_cp (Failed)
I attach the latest LastTest.log file. Thank you.

[LastTest_5_Dec.log](https://github.com/relic-toolkit/relic/files/2649128/LastTest_5_Dec.log)

**Comment by cjpn** [comment]
The code now compiles and the tests run without error. The tests also run more quickly, which is a bonus. 

100% tests passed, 0 tests failed out of 18
Total Test time (real) = 1782.85 sec

Thank you.

**Comment by xidianouwen** [comment]
Hi,
I get the same problem when trying to build the relic library with the command 'make', it seems that there is no definition about the type unsigned int for 128 bit, and  I'm in  VM with Ubuntu 16.04, I have updated my gcc compiler from  5.4 to 6 and it does not work,  I also went into <stdint.h> and find there is no definition related to __uint128.

What can i do?
Thank you.

In file included from /home/woshinidie/relic/relic/include/relic_arch.h:39:0,
                 from /home/woshinidie/relic/relic/include/relic_util.h:39,
                 from /home/woshinidie/relic/relic/include/relic_err.h:42,
                 from /home/woshinidie/relic/relic/include/relic_core.h:48,
                 from /home/woshinidie/relic/relic/src/relic_err.c:37:
/home/woshinidie/relic/relic/include/relic_types.h:125:9: error: unknown type name ‘__uint128_t’
 typedef __uint128_t dbl_t;
         ^~~~~~~~~~~
src/CMakeFiles/relic_s.dir/build.make:62: recipe for target 'src/CMakeFiles/relic_s.dir/relic_err.c.o' failed
make[2]: *** [src/CMakeFiles/relic_s.dir/relic_err.c.o] Error 1
CMakeFiles/Makefile2:86: recipe for target 'src/CMakeFiles/relic_s.dir/all' failed
make[1]: *** [src/CMakeFiles/relic_s.dir/all] Error 2
Makefile:138: recipe for target 'all' failed
make: *** [all] Error 2

**Comment by dfaranha** [comment]
You should change the configuration with `-DWSIZE=32`, as it looks you're building on a 32-bit platform.

**Comment by xidianouwen** [comment]
> You should change the configuration with `-DWSIZE=32`, as it looks you're building on a 32-bit platform.

Oh I get it, thank you
