### ISSUE TITLE
RELIC naming conflict

### ISSUE THREAD

**Issue by wangxiao1254** [relic-toolkit/relic#106]
Relic was working on MacOS without modification but now there is a naming conflict.

`sig_t` is already defined in, e.g. open BSD. https://github.com/openbsd/src/blob/master/sys/sys/signal.h#L146

See 
https://travis-ci.org/emp-toolkit/emp-tool/jobs/523981309#L1901
for errors.

**Comment by dfaranha** [comment]
I just reverted this change, it should compile again.

Nice to see you here! I think I saw that emp-toolkit uses the curve2251 implementation in RELIC, so you should know that our faster GLS254 implementation is coming soon to the library. :)

**Comment by wangxiao1254** [comment]
Thanks! Everything is working now!

That's awesome, RELIC is great!!
