### ISSUE TITLE
Removal of NAFWI and YAOWI precomputation methods

### ISSUE THREAD

**Issue by thandirk** [relic-toolkit/relic#107]
Why were the YAOWI and NAFWI precomputation methods removed in commit d17c5a52200c80359fa166ea5356750d035391c1? The commit message says there are faster alternatives, however according to my benchmarking results in the curve BN_P254 ep_mul_fix_nafwi and ep2_mul_fix_yaowi are the fastest of all the ep_mul_fix and ep2_mul_fix functions. Thus, with a large enough number multiplications these methods will make up the time difference of the longer mul_pre functions.

The full results of my benchmarks are the following:
-- Curve BN-P254:
-- Group G_1:
BENCH: ep_mul_pre_basic                 = 6976 microsec
BENCH: ep_mul_fix_basic                 = 2333 microsec
BENCH: ep_mul_pre_yaowi                 = 4124 microsec
BENCH: ep_mul_fix_yaowi                 = 1698 microsec
BENCH: ep_mul_pre_nafwi                 = 3863 microsec
BENCH: ep_mul_fix_nafwi                 = 1271 microsec
BENCH: ep_mul_pre_combs                 = 1502 microsec
BENCH: ep_mul_fix_combs                 = 1472 microsec
BENCH: ep_mul_pre_combd                 = 8329 microsec
BENCH: ep_mul_fix_combd                 = 1385 microsec
BENCH: ep_mul_pre_lwnaf                 = 144 microsec
BENCH: ep_mul_fix_lwnaf                 = 3860 microsec

-- Group G_2:
BENCH: ep2_mul_pre_basic                = 5969 microsec
BENCH: ep2_mul_fix_basic                = 5093 microsec
BENCH: ep2_mul_pre_yaowi                = 10249 microsec
BENCH: ep2_mul_fix_yaowi                = 2265 microsec
BENCH: ep2_mul_pre_nafwi                = 5961 microsec
BENCH: ep2_mul_fix_nafwi                = 2806 microsec
BENCH: ep2_mul_pre_combs                = 5311 microsec
BENCH: ep2_mul_fix_combs                = 3197 microsec
BENCH: ep2_mul_pre_combd                = 17152 microsec
BENCH: ep2_mul_fix_combd                = 2439 microsec
BENCH: ep2_mul_pre_lwnaf                = 253 microsec
BENCH: ep2_mul_fix_lwnaf                = 7425 microsec

**Comment by dfaranha** [comment]
Hi,

I'm assuming that the default value for EP_DEPTH of 4 is being used here for these timings. This means that NAFWI and YAOWI are indeed slightly faster, but use much more memory in the precomputation tables than COMB. Can you please check if the trend looks the same for the more realistic values for EP_DEPTH (e or 8, perhaps)?

**Comment by thandirk** [comment]
Hi,
yes I was using EP_DEPTH=4. For larger values of EP_DEPTH the COMB methods are indeed faster than NAFWI and YAOWI. 
Thanks for the answer.
