### ISSUE TITLE
Bug in cp_bbs_sig

### ISSUE THREAD

**Issue by mspecter** [relic-toolkit/relic#108]
I think there may be a bug in the cp_bbs_sig function.

In particular, the signature is supposed to be s = 1/(m+d) * g1. It appears that the function calculates the BN portion, and sets it to some variable r = 1/(m+d) (see line 106 in src/cp/relic_cp_bbs.c), but the result (r) is never actually used. Instead, the function discards r and calculates g1 * (m mod n). 

Perhaps this passes the test suite because the tests all use a very short message? Or am I confused?

**Comment by dfaranha** [comment]
The syntax of bn_gcd_ext is indeed confusing. What the function is doing is actually computing the inverse of (m+d) modulo n (group order) and storing the result back to m. The GCD is also computed as a side-effect and returned in r, which has no use inside this function and ends being discarded. The bit handling negative signals is also tricky.

I want to soon introduce a bn_mod_inv() wrapper function that has a simpler syntax and prevents this type of confusion.

**Comment by mspecter** [comment]
Oh, I see! The source of my confusion is the documentation for bn_gcd_ext which appears to only modify the first operand C (See include/relic_bn.h, 351): 
bn_gcd_ext(C, D, E, A, B)
"Computes c = gcd(a, b) and c = a * d + b * e."

However, it appears that if you set E to null, the function works as you describe (e.g. in src/bn/relic_bn_gcd.c). Thanks!
