### ISSUE TITLE
Bilinear map pairing for FP_PRIME=381 crashes

### ISSUE THREAD

**Issue by mspecter** [relic-toolkit/relic#109]
It appears that the bilinear map pairing operation for a BLS 381 curve will crash!

How to Reproduce
1. Compile using preset/x64-pbc-128-b12.sh
2. run bin/test_pc

You'll see a loop of:
FATAL ERROR in relic_fp_param.c:358

My System: Fresh docker image of Ubuntu LTS
```
uname -a
Linux 5855a0ee7c1f 4.9.125-linuxkit #1 SMP Fri Sep 7 08:20:28 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux
```

**Comment by dfaranha** [comment]
Indeed, my latest commits should fix this. Can you please confirm?

**Comment by mspecter** [comment]
Yes! Thank you so much, this appears to be fixed! 

Quick question, I notice that there are tags / releases, but they're from quite a while ago, do you all intend to have a "stable" release of this any time soon? 

In any case, thanks for the amazing project!

**Comment by dfaranha** [comment]
Yes, we are moving towards a 0.5.0 release, but I'm waiting for things to be less crappy and broken before doing it. Thanks! :)
