### ISSUE TITLE
pc_map() / pp_map_k12() work only for normalized points

### ISSUE THREAD

**Issue by 1gn1t10n** [relic-toolkit/relic#11]
#### Context
RELIC version: 1d085285a37f75bdbddf1c1c7dce7af3d0bd4d3e
Configure parameters: `-DDEBUG=on -DBENCH=10 -DTESTS=10 -DARITH=gmp -DALLOC=DYNAMIC -DBN_PRECI=8192 -DFP_PRIME=256`

#### Issue
`pc_map()` / `pp_map_k12()` silently fail when one of the arguments (element of G1 or G2) is not normalized.

#### Possible fix
Adapt the method to handle such inputs or update the documentation to inform the programmer about this requirement.

#### Note
This might apply to `pp_map_k2()` as well.

**Comment by dfaranha** [comment]
This took me a while, should have been fixed for all curves and pairings! Thanks again for reporting!
