### ISSUE TITLE
Ready for release?

### ISSUE THREAD

**Issue by swedebugia** [relic-toolkit/relic#113]
Hi 
I see no release has been made since 2014. 
Could you make one?
I ask because this is a build dependency of bls-signatures and dashcore and i'm packaging it for Guix.

**Comment by dfaranha** [comment]
I hope to have a new release soon, but there are still bugs to fix in the ED module that prevent that from happening now. Hopefully there will be a new version before the end of July (during my holidays).

**Comment by dfaranha** [comment]
I just made a release of version 0.5.0, hope it helps!
