### ISSUE TITLE
CMake building fails with curve2251-sse and add_subdirectory

### ISSUE THREAD

**Issue by MartKro** [relic-toolkit/relic#114]
Hello there,

When trying to include the relic library using add_subdirectory the library cannot be built when using specific configurations.

The reason for that is at /src/low/curve2251-sse the first line include(${CMAKE_SOURCE_DIR}/cmake/gmp.cmake) which points to the top level, and not to the top level of the project.

I'd like to change this line into something like include(${PROJECT_SOURCE_DIR}/cmake/gmp.cmake) since I don't see any reason it's useful to always point to the top level and not to the top level of the project.

**Comment by dfaranha** [comment]
It was probably my lack of familiarity with CMake.

Can you please submit a Pull Request with something that works for you? :)
