### ISSUE TITLE
test_epx fails

### ISSUE THREAD

**Issue by mogisawa** [relic-toolkit/relic#116]
Hi, Diego. I started to enjoy relic in the last few weeks.
I run the tests, but `test_epx` fails at "cubed frobenius is consistent".
So I read `relic_fpx_field.c` with some doubt for `ctx->fp2_p3`.
I don't know details of the table. By luck, I found a way to let the test pass.
At line 118 of `relic_fpx_field.c`, add `if (i >= 3) ...` state.
```
		for (int i = 0; i < 5; i++) {
			fp_mul(ctx->fp2_p3[i][0], ctx->fp2_p2[i % 3], ctx->fp2_p[i][0]);
			fp_mul(ctx->fp2_p3[i][1], ctx->fp2_p2[i % 3], ctx->fp2_p[i][1]);
			if (i >= 3) {
				fp2_neg(ctx->fp2_p3[i], ctx->fp2_p3[i]);
			}
		}
```
When i=0 or i=3, both takes `fp2_p2[i % 3]`.
I wondered that some difference may be needed for not only `fp2_p[i]` but `fp2_p2[i % 3]` also.
I hope it helps you.

**Comment by dfaranha** [comment]
Thanks, fixed in the repository! I just pushed a commit to simplify ep2_frb() that should make this better. I am now working in streamlining fpx_frb functions and precomputed constants, because the current version is very messy.
