### ISSUE TITLE
Cofactor in G2 is now not implmented

### ISSUE THREAD

**Issue by mogisawa** [relic-toolkit/relic#117]
Hi, Diego.
The cofactor of ep2 is set 1 in `ep2_curve_set_twist`.
```
/* TODO: support non-trivial cofactors. */
		bn_set_dig(&(ctx->ep2_h), 1);
```
So `ep2_curve_get_cof` have a wrong return(always 1).
It should return an error or a right value.(Especially 1 is too difficult to notice the wrong implementation.)
By the way, I made a script which computes the cofactor of BN, BLS12, BLS24 and BLS48.
[https://github.com/mogisawa/gencofactor](url)
Please use it if you like.

**Comment by dfaranha** [comment]
Hi, thanks for the script! :)

All curves defined over Fp2 now have non-trivial co-factors, although hashing still uses faster decompositions whenever possible.
