### ISSUE TITLE
ARM64 support

### ISSUE THREAD

**Issue by liorko87** [relic-toolkit/relic#119]
I'm trying to compile relic library on Ubuntu 18.04 on ARM64 on AWS (`march=aarch64`).
During the compilation I received this error:
```
error: #error "Unsupported ARM architecture. Cycle count implementation missing for this ARM version."
#error "Unsupported ARM architecture. Cycle count implementation missing for this ARM version."
```
The compilation done using: `cmake. -DARCH=ARM -DWSIZE=64`

**Comment by dfaranha** [comment]
Can you try building with -DTIMER=HPROC?
This should give you performance figures in nanoseconds (instead of cycles).

**Comment by liorko87** [comment]
@dfaranha Thank you for your quick answer.
I needed also to change `-DARITH=curve2251-sse` to `-DARITH=GMP`
