### ISSUE TITLE
Feedback on library interface

### ISSUE THREAD

**Issue by 1gn1t10n** [relic-toolkit/relic#12]
Instead of opening multiple individual issues, I grouped here a few behaviours that seemed a bit unusual from a library user's perspective.
#### Comparison routines

Comparison routines like `ep_cmp` / `g1_cmp` expect the points / group elements to be normalized. The comparison fails otherwise.

I understand that normalizing the points _in_ the comparison function could be a side-effect that the programmer might not expect. This is why the arguments are `const`.

A possible solution would be to internally duplicate the points, normalize them, and only then compare them.

Another less resource-heavy solution would be to udpate the documenation to warn about this behaviour.
#### Methods taking elements in Zn

As I started to use the library I was left with the impression that the best way to handle elements in Zn is by using the `bn_t` type. This feeling is confirmed by the API of many functions that use `bn_t` when they expect an element in `Zn`.

However, there are some inconsistencies which break this unspoken promise, sometimes to the detriment of performance, sometimes even for correctness. Additive or multiplicative notation, applies to both:
- One has to compute `-x\*g` as `- (x\*g)`. Doing `(-x) * g` fails silently. More explicitly, one has to do

```
        g2_mul(g_x, g, x);
        g2_neg(g_x, g_x);
```

instead of

```
      bn_neg(tmp, x);
      g2_mul(g_x, g, tmp);
```
- g^0 is not 1 (it crashes). See #9 
- g^exp when exp >> n (where n is the modulo in Zn) makes the library exit due to insufficient buffer capacity. Which means that exp is not treated modulo n, so even when it doesn't crash, it is possibly slower.
#### In general

Many methods expect some inputs to be in a very specific format in order to work correctly. Although this might be obvious for somebody familiar with the implementation of the library, it might come as a surprise for somebody using the library as a blackbox to experiment with a cryptographic protocol.

One way to mitigate this is to sanitize inputs and make the library more robust.

Another way would be to change the documentation such that it is clear what a programmer should do in order for the library to work correctly.

**Comment by dfaranha** [comment]
Thanks a lot for this! We don't have many users and your effort is tremendously helpful.

I'm planning to chop off some of the library features to make the code base a little easier to handle, so let me ask you: do you have a specific reason to use ALLOC = DYNAMIC in your examples?

**Comment by dfaranha** [comment]
Here is a first try at solving the ep_cmp() issue. It's somewhat complicated to handle all the possible inputs:

```
int ep_cmp(const ep_t p, const ep_t q) {
	ep_t r, s;
	int result = CMP_EQ;

	ep_null(r);
	ep_null(s);

	TRY {
		ep_new(r);
		ep_new(s);

		if ((!p->norm) && (!q->norm)) {
			/* If the two points are not normalized, it is faster to compare
			 * x1 * z2 == x2 * z1 and y1 * z2^2 == y2 * z1^2. */
			fp_mul(r->x, p->x, q->z);
			fp_mul(s->x, q->x, p->z);
			fp_sqr(r->z, p->z);
			fp_sqr(s->z, q->z);			
			fp_mul(r->y, p->y, s->z);
			fp_mul(s->y, q->y, r->z);
		} else {
			if (!p->norm) {
				ep_norm(r, p);
			} else {
				ep_copy(r, p);
			}

			if (!q->norm) {
				ep_norm(s, q);
			} else {
				ep_copy(s, q);
			}
		}

		if (fp_cmp(r->x, s->x) != CMP_EQ) {
			result = CMP_NE;
		}

		if (fp_cmp(r->y, s->y) != CMP_EQ) {
			result = CMP_NE;
		}
	} CATCH_ANY {
		THROW(ERR_CAUGHT);
	} FINALLY {
		ep_free(r);
		ep_free(s);
	}

	return result;
}
```

**Comment by dfaranha** [comment]
Hi @1gn1t10n,

Following your feedback, I have implemented a great deal of checks across the library.
The only ones from this thread I am still missing is reducing exponents in G1 and G2 modulo the group order, which should not cause as much hassle as in GT.

Thanks again for the feedback!
