### ISSUE TITLE
MSVC / Windows compilation problem with local static variable

### ISSUE THREAD

**Issue by KrishnaPG** [relic-toolkit/relic#120]
The `default_color` variable defined locally in the `relic_test.c` file is causing build problem with MSVC on Windows. It is defined inside a function, but being accessed from another method.

https://github.com/relic-toolkit/relic/blob/a542f0510d7540cbaf16fc0a967e347020dc17a8/src/relic_test.c#L86

https://github.com/relic-toolkit/relic/blob/a542f0510d7540cbaf16fc0a967e347020dc17a8/src/relic_test.c#L127

Separating the variable `default_color` declaration into file scope could fix the issue. Please look into it.

**Comment by dfaranha** [comment]
Thanks for the notification! Can you please send a PR with the fix? :)

**Comment by KrishnaPG** [comment]
PR https://github.com/relic-toolkit/relic/pull/121
