### ISSUE TITLE
Incorrect result for bn_sub(...) for zero operand.

### ISSUE THREAD

**Issue by ladnir** [relic-toolkit/relic#127]
There is a logic error in the `bn_sub` function. Given the following pseudo code
```
bn_t a = 0;
bn_t b = 2341234; // any positive, 
bn_t c;

bn_sub(c,a,b);
c ==  2341234;
```

This issue happens [here](https://github.com/relic-toolkit/relic/blob/master/src/bn/relic_bn_add.c#L191) and [here](https://github.com/relic-toolkit/relic/blob/master/src/bn/relic_bn_add.c#L90). 

Specifically, inside `bn_sub` it does some optimization for `a<b` and tries to compute `b-a` and then flip the sign to get `a-b`. However, when `a=0` what the lower level subtraction does is a copy of `b` into `c` which overwrites the flipping of the sign that was done  [here](https://github.com/relic-toolkit/relic/blob/master/src/bn/relic_bn_add.c#L191).

I can write PR but I got the impression that there might be some subtleties that I could miss...

**Comment by dfaranha** [comment]
Thanks for the notification! My latest commit just moved the sign computation to after the function call, as to avoid interference as a better practice.

In the long term, I'm planning a rewrite of the entire BN modular to use 2's complement for constant time guarantees, but until then the library has to live with the old code.

**Comment by ladnir** [comment]
Thanks for the update and your work on Relic :)
