### ISSUE TITLE
Overflow in bn_rec_tnaf_get()

### ISSUE THREAD

**Issue by OlegHahm** [relic-toolkit/relic#13]
My compiler (gcc (GCC) 4.9.2 20150204 (prerelease)) is warning about an `overflow in implicit constant conversion` in https://github.com/relic-toolkit/relic/blob/master/src/bn/relic_bn_rec.c#L242 and to my understanding that's true. `t` is an `int8_t` pointer and `166` is > 2^8/2.

**Comment by dfaranha** [comment]
Changed to the pointer to uint8_t, as the t_w value is by definition positive. Thanks for reporting!
