### ISSUE TITLE
Two representations of BN zero are not equal

### ISSUE THREAD

**Issue by kibuff** [relic-toolkit/relic#135]
According to [bn_is_zero](https://github.com/relic-toolkit/relic/blob/86e1208f5402969e85c77adaca2faf3e9cb134aa/src/bn/relic_bn_util.c#L87), zero has two representations:

```c
int bn_is_zero(const bn_t a) {
	if (a->used == 0) {
		return 1;
	}
	if ((a->used == 1) && (a->dp[0] == 0)) {
		return 1;
	}
	return 0;
}
```

However, if I use [bn_cmp](https://github.com/relic-toolkit/relic/blob/86e1208f5402969e85c77adaca2faf3e9cb134aa/src/bn/relic_bn_cmp.c#L71) with one of these representations each as parameter, bn_cmp does not return RLC_EQ.

**Comment by dfaranha** [comment]
It should be fixed in the latest commit.
