### ISSUE TITLE
g2_map() produce invalid points

### ISSUE THREAD

**Issue by laurent-girod** [relic-toolkit/relic#148]
While working on [Petrelic](https://github.com/spring-epfl/petrelic), I noticed that some tests were no longer passing after after updating Relic. We identified two likely bugs, one related to the `*_is_valid()` functions, and one related to the `g2_map()` function.

This issue is the bug related to the `g2_map()` function.

After some tests, I noticed that `g2_map()` was producing invalid points.

I suspected that this might be related to the other issue related to the `*_is_valid()` functions, but even after normalizing the point, `g2_is_valid()` return that the point is not valid.

```c
g2_map(p, "Hello!", 6);
g2_norm(p, p);
res = g2_is_valid(p); // res = 0
```

**Comment by dfaranha** [comment]
This seems related to the new complete formulas I have recently implemented. I just managed to reproduce and will take a closer look in the holiday tomorrow.

**Comment by dfaranha** [comment]
This should be fixed now, with an ugly temporary hack.

**Comment by laurent-girod** [comment]
Thank you, I confirm that the fix works. :-)
