### ISSUE TITLE
Name clashes between RELIC and OpenSSL in C++

### ISSUE THREAD

**Issue by 1gn1t10n** [relic-toolkit/relic#16]
RELIC version: 706f38e302336f84ac29151ed8b1e32b8835eb75
OpenSSL version: 1.0.1k

RELIC and OpenSSL don't work together when used in a C++ program. Some of the problems are:
- `usr/include/relic/relic_bn.h:54:0: warning: "BN_BITS" redefined`
- `usr/include/relic/relic_bn.h:74:0: warning: "BN_BYTES" redefined`
- `usr/include/relic/relic_cp.h:97:3: error: conflicting declaration ‘typedef struct _rsa_t rsa_st’`

I noticed OpenSSL guards the include files in `extern "C"`. RELIC doesn't. Apart from that, I don't understand much more.

I'm using RELIC for pairings and OpenSSL for the AES implementation. Through the EVP interface, it has AES-NI support and it also has more modes of operations (ie CTR). RELIC has only CBC.

**Comment by dfaranha** [comment]
I just prefixed many macros within the library, so most of these problems should go away now. :)
