### ISSUE TITLE
Segmentation fault in pc_map_sim

### ISSUE THREAD

**Issue by mariano54** [relic-toolkit/relic#160]
Hello, I am verifying 10,000 signatures using BLS12-381 curve and pc_map_sim (OATEP), and I get a segmentation fault.
Is there a limit to the number of signatures that can be validated with pc_map_sim?

Mac os 10.15.5
3.5 GHz Dual-Core Intel Core i7
16GB ram

Thank you,

Mariano

**Comment by dfaranha** [comment]
RELIC uses stack allocation by default, and memory for 10,000 signatures will certainly fail allocation.
Can you try rebuilding with -DALLOC=DYNAMIC or increasing the process size?

**Comment by mariano54** [comment]
OK I will try to get it running with DYNAMIC, thanks.

**Comment by dfaranha** [comment]
BTW, have you considered aggregating these signatures before verification?
