### ISSUE TITLE
Recent problem with fp_prime_conv

### ISSUE THREAD

**Issue by wjblanke** [relic-toolkit/relic#163]
This Relic commit breaks the tests in our project:

https://github.com/relic-toolkit/relic/commit/bb41dc8871244c9abd23268ca065d459a68b79eb

I narrowed it down to the new code in fp_prime_conv():

#if FP_RDC == MONTY
    fp_mul(c, t->dp, core_get()->conv.dp);
#else

If I replace it with the old code, our project tests pass fine:

#if FP_RDC == MONTY
    bn_lsh(t, t, RLC_FP_DIGS * RLC_DIG);
    bn_mod(t, t, &(core_get()->prime));	
    dv_copy(c, t->dp, RLC_FP_DIGS);	
#else

Since this was an optimization, I wouldn't think behavior would change, unless fp_prime_conv() makes stricter assumptions on the inputs passed to it or output generated? Or maybe there is a bug?

We've pinned to the previous commit for the time being. Let me know if I can help in any way! Cheers

**Comment by dfaranha** [comment]
It was a bug due to a (common) corner case, it should be fixed by now.

**Comment by hoffmang9** [comment]
Looks to be fixed.
https://github.com/Chia-Network/bls-signatures/pull/138
