### ISSUE TITLE
Memory leak in ep2_curve_init/clean with ALLOC=DYNAMIC

### ISSUE THREAD

**Issue by jakubdabek** [relic-toolkit/relic#166]
There are a couple of allocations in `ep2_curve_init` that are not cleaned up in `ep2_curve_clean`.
Probably introduced in 9b0a8f2c2288f9ec0cb1a62c9ad103ad478677a9, where commit message talks about cleaning up, but changes don't include corresponding calls to `*_free`.

Found with valgrind on current master.

**Comment by dfaranha** [comment]
Thanks for reporting! I just pushed a fix, please let me know if you see an improvement.

**Comment by jakubdabek** [comment]
Looks good now 👍
