### ISSUE TITLE
 ‘ctx_t’ {aka ‘struct _ctx_t’} has no member named ‘total’

### ISSUE THREAD

**Issue by xiahaijiao** [relic-toolkit/relic#168]
relic_bench.c:166:12: error: ‘ctx_t’ {aka ‘struct _ctx_t’} has no member named ‘total’
  core_get()->total = 0;

**Comment by dfaranha** [comment]
I cannot reproduce. What is your config?

**Comment by dfaranha** [comment]
Closing due to difficulty in reproducing.
