### ISSUE TITLE
Building Relic with Curve NIST_P256 throws FATAL ERROR in relic_fp_prime.c:120

### ISSUE THREAD

**Issue by Sn0wfreezeDev** [relic-toolkit/relic#170]
Hi, 

thank you very much for this nice library that allows me to quickly build custom operations with elliptic curves. Today I wanted to change the default curve used to NIST_P256 for some tests. For this I changed FP_PRIME to 256 and defined EP_PLAIN in the relic_conf.h before I initiated a new build. 
To initialize relic I call `core_init()` and `ep_param_set_any_plain()`. When I call `ep_param_set_any_plain()` I always get an error in the logs `FATAL ERROR in /.../libraries/relic/src/fp/relic_fp_prime.c:120`. It looks like the error would report an error when setting up the curve, but the function returns `RLC_OK` (0) and using the curve works as expected. Furthermore, I checked the field parameter identifier with `fp_param_get()` and it reports the NIST_256 parameter. 

I run the library on iOS and macOS and both devices are able to communicate, because they use a similar relic_conf with the same curve settings. 

So it looks like the error does not influence the behavior and correctness, but I wanted to make sure to know what it means and how to resolve it. 

Kind regards, 
Alex 

___
relic_conf.h parameters: 
```
/** Support for ordinary curves. */
#define EP_PLAIN

/** Prime field size in bits. */
#define FP_PRIME 256
```

Initialization 
```
if (core_init() != RLC_OK) {
    core_clean()
}

let initPlain = ep_param_set_any_plain()
if (initPlain != RLC_OK) {
    core_clean()
}
```

**Comment by dfaranha** [comment]
Thank you for your notification!

What version of the library are you running? Line 120 in the repository version does not have an exception being thrown. Can you also check that FP_QNRES is turned off? It matters only for curves equipped with bilinear pairings and could throw such exceptions.

**Comment by Sn0wfreezeDev** [comment]
Thank you, I updated to 0.5.0 (I was probably using 0.4.0) and disabled FP_QNRES and it solved the issue.
