### ISSUE TITLE
Builds are broken

### ISSUE THREAD

**Issue by schanzen** [relic-toolkit/relic#178]
Hi,

in commit https://github.com/relic-toolkit/relic/commit/4d03fcc21f9938153f8032a6ef74306ffb732232#diff-1e7de1ae2d059d21e1dd75d5812d5a34b0222cef273b7c3a2af62eb747f9d20aR233 the build system was changed to use CFLAGS from the environment. However, this means that CFLAGS can no longer be set using cmake variables (cmake -DCFLAGS=...).

This breaks our build as it is using relic as an ExternalProject and sets the CFLAGS(previously COMP).
But, it also breaks all of your builds in "preset/" as they all use the -DCOMP/now -DCFLAGS as well.

To test:
- Run any preset
- Observe CFLAGS are not properly set

To fix:
- Use the same logic as for COMP previously: Check for the $ENV, but ALWAYS use the variable, not the ENV when setting the flags.
- Note that changing the builds in preset/ to use environment variables will fix those, but anyone using ExternalProject_add to include relic will not be able to set CFLAGS as cmake does not allow setting ENV for those.

BR
Martin

**Comment by dfaranha** [comment]
Thank you for the notification. I just pushed commit 4efce04ad28574a7f27095e97d198313fd5b8821 to cache CFLAGS and hopefully restore the previous functionality.

Can you please check?

**Comment by schanzen** [comment]
This fixes the issue for me. Thanks!
