### ISSUE TITLE
Tests FTBFS because of missing symbol in header

### ISSUE THREAD

**Issue by schanzen** [relic-toolkit/relic#179]
Under macos, relic fails to build for me because a test is missing a symbol.
Actually, the symbols are compiled, but not defined in the respective header (include/relic_fpx.h)

The offending symbols are: fp12_pck_max / fp12_upk_max

And the build fails like this:

src/relic/test/test_fpx.c:4475:4: error: implicit declaration of function 'fp12_pck_max' is invalid in C99
      [-Werror,-Wimplicit-function-declaration]
                        fp12_pck_max(b, a);
src/relic/test/test_fpx.c:4476:16: error: implicit declaration of function 'fp12_upk_max' is invalid in C99
      [-Werror,-Wimplicit-function-declaration]
                        TEST_ASSERT(fp12_upk_max(c, b) == 1, end);

**Comment by schanzen** [comment]
The solution is to simply add the functions to the header, but I am not sure how to produce a correct comment. Hence no pull request.

BR

**Comment by dfaranha** [comment]
Done! Let me know if something else is also failing.

**Comment by schanzen** [comment]
This issue is fixed for me now. Thanks!
