### ISSUE TITLE
make error: conflicting types for ‘bn_mula_low’

### ISSUE THREAD

**Issue by Arash-Afshar** [relic-toolkit/relic#18]
When compiling 
src/CMakeFiles/relic.dir/low/curve2251-sse/relic_bn_mul_low.c.o

it throws the following error:
low/curve2251-sse/relic_bn_mul_low.c:42:7: error: conflicting types for ‘bn_mula_low’
low/relic_bn_low.h:206:7: note: previous declaration of ‘bn_mula_low’ was here

**Comment by dfaranha** [comment]
Thanks for reporting! This should be fixed now and the presets were added to the Buildbot so it does not happen again.
