### ISSUE TITLE
[BUG] undefined reference to `bench_init', `bench_clean'

### ISSUE THREAD

**Issue by hoffmang9** [relic-toolkit/relic#180]
I'm not sure if this is a bug or just an intended breaking change.

When linking bls-library to relic origin/master we're getting the following error:
```
../_deps/relic-build/lib/librelic_s.a(relic_core.c.o): In function `core_init':
src/CMakeFiles/runbench.dir/build.make:106: recipe for target 'src/runbench' failed
relic_core.c:(.text+0x40): undefined reference to `bench_init'
CMakeFiles/Makefile2:310: recipe for target 'src/CMakeFiles/runbench.dir/all' failed
../_deps/relic-build/lib/librelic_s.a(relic_core.c.o): In function `core_clean':
relic_core.c:(.text+0x9d): undefined reference to `bench_clean'
```
https://github.com/Chia-Network/bls-signatures/runs/1788109386?check_suite_focus=true#step:6:1532

Worked fine at https://github.com/relic-toolkit/relic/commit/eae53669910a69aa6f83468be86d8f815bf23ff1

Clearly fails against https://github.com/relic-toolkit/relic/commit/0e7f7d46ef20811aeee06721363c8a980907831d

We pinned to https://github.com/relic-toolkit/relic/commit/cdd71de5392aadac29e8b3be27bf605baaf4ad25 for now.

**Comment by hoffmang9** [comment]
Also just figured out you probably know from CI. - https://travis-ci.org/github/relic-toolkit/relic/jobs/756608564

**Comment by dfaranha** [comment]
It should be fixed now.

CI was showing "passing" here, so I thought it was fine =/

**Comment by hoffmang9** [comment]
Confirmed that master aka 33d154b3eb591e03ae8f3ae3665f4031d5ff686b is working now.

**Comment by hoffmang9** [comment]
And thanks!
