### ISSUE TITLE
Compilation of RELIC with bls12-446 and bls12-455 fails

### ISSUE THREAD

**Issue by adelapie** [relic-toolkit/relic#182]
Hello,

I'm trying to compile RELIC using the presets for x64 and curves bls12-446 /  bls12-455.
However, compilation fails with this message:

/usr/bin/ld: ../lib/librelic_s.a(relic_fp_add.c.o): in function `fp_dbl_basic':
relic_fp_add.c:(.text+0x209): undefined reference to `fp_lsh1_low'

**Comment by dfaranha** [comment]
Thank you for the notification!

There was indeed a minor refactoring to reduce the amount of duplicated code, but it should be fixed now.

Can you please check?

**Comment by adelapie** [comment]
It works now, thanks a lot!
