### ISSUE TITLE
arch_cycles fails on Windows MSVC 64 bit

### ISSUE THREAD

**Issue by wjblanke** [relic-toolkit/relic#188]
arch_cycles uses inline assembly which is not allowed when compiling on MSVC 64 bit

**Comment by wjblanke** [comment]
looks like sys/time.h is missing for HREAL. I'm just returning 0 for now as it looks like it is only used by the benchmark

**Comment by dfaranha** [comment]
There are also TIMER=ANSI or TIMER=POSIX for other alternatives.

**Comment by dfaranha** [comment]
Function clock_gettime() is apparently provided by winpthreads:

https://github.com/Alexpux/mingw-w64/blob/master/mingw-w64-libraries/winpthreads/src/clock.c
