### ISSUE TITLE
Parameters of the BN curves

### ISSUE THREAD

**Issue by luozejiaqun** [relic-toolkit/relic#192]
I want to add a new BN curve with the following parameters:
t ：60000000 0058F98A
b :  5
twist parameter : sqrt(-2)
and the generator of the curve and twisted curve.
But I find that I have to provide the GLV parameters beta and lamb. That's not all, I also have to calculate the b-coefficient of the twisted curve. I have no idea how to calculate those coefficients with the given twist parameter. So, is there any tools or scripts that can calculate the GLV parameters and the b-coefficient of the twisted curve?

**Comment by dfaranha** [comment]
Hi,

The latest version of the library should take care of lambda and beta for BN curves. Is there something special about this curve that can motivate its inclusion in the library in a more official capacity?

**Comment by luozejiaqun** [comment]
This BN curve is the standard curve of SM9 which is a cryptographic hash algorithm published by the State Cryptography Administration of China. Here is the documents [The SM9 Identity-Based Cryptographic Algorithms](https://www.ietf.org/staging/draft-sca-cfrg-sm9-00.txt).

**Comment by chinsyo** [comment]
SM9 algorithm has been widely used for cyber security and privacy protection purpose.

Here is some reference:
- [ISO/IEC 18033-5:2015](https://www.iso.org/standard/59948.html) SM9 identity on the basis of the findings was standardized in IEEE 1363.3, in ISO / IEC 18033-5:2015 and the IETF in RFC 6508.
- [ISO/IEC 14888-3:2018](https://www.iso.org/standard/76382.html) Signature algorithm based SM9 identity was standardized in IEEE 1363.3 and ISO / IEC 14888-3:2015.
- [ISO/IEC 11770-3:2015](https://www.iso.org/standard/60237.html) SM9 bilinear pairing based key establishment mechanisms was standardized in ISO / IEC 11770-3:2015.

**Comment by dfaranha** [comment]
Hi,

I added some support to this curve in `17b295042732848b9823b876101f0cb92dbdd6b4`. It seems like the pairing-based protocols work, but the tower arithmetic is failing for the quartic and its upper extensions, not sure why.

**Comment by YuriMzz** [comment]
Hi, i have a question about curves parameters:
can you provide the t parameter used to generate each BN and BLS curve? I would like to validate the security levels of them with the apha software (https://gitlab.inria.fr/tnfs-alpha/alpha) bui i need to identify the specific curve. 
In some papers this parameter is also called u.

**Comment by dfaranha** [comment]
You can find these values for the supported curves in https://github.com/relic-toolkit/relic/blob/main/src/fp/relic_fp_param.c
