### ISSUE TITLE
16-bit MSP430

### ISSUE THREAD

**Issue by decoder1799** [relic-toolkit/relic#193]
Hi, I am looking for bringing some security solutions to MSP430 based devices. It is 16-bit RISC architecture. Can someone please help me in getting started with it?
Thanks in advance!!

**Comment by dfaranha** [comment]
@conradoplg is the right person for the job.

**Comment by dfaranha** [comment]
Given the silence, an alternate suggestion: please write to the RELIC mailing `relic-discuss@googlegroups.com`, it's more likely you can get help there.

Good luck!

**Comment by conradoplg** [comment]
Sorry for taking so long. @decoder1799 , we'd need more information about what exactly you need to accomplish.

RELIC can help you by providing a C library to carry out common cryptography tasks, but there are also other libraries which are more popular and you may have an easier time with support (e.g. mbedTLS).
RELIC is more appropriate if performance is critical, then you could use the MSP430 assembly backend. Its code size is very big, however (~40KB), so it may not be appropriate for your case.
RELIC is a algo a good choice if you need support for more "esoteric" protocols like the pairing-based ones. In that case you can use the C backend if code size is an issue. But also in that case it will be just a C library, so the fact that it's a MSP430 won't affect it very much.
