### ISSUE TITLE
-DMD_METHD=B2S160 -DMD_MAP=B2S160 compilation in presets

### ISSUE THREAD

**Issue by adelapie** [relic-toolkit/relic#195]
Hello,

Is it possible to use a different hash for mappings in the presets ? For instance, adding -DMD_METHD=B2S160 -DMD_MAP=B2S160 to x64-pbc-bls12-381.sh:

```
relic/src/md/relic_md_hmac.c:50:18: error: ‘block_size’ undeclared (first use in this function)
   50 |     uint8_t opad[block_size + RLC_MD_LEN];
```

**Comment by dfaranha** [comment]
That was a bug, now fixed/pushed. However, the XMD functions still not compile, and I'm not sure such a function has been instantiated with BLAKE 2.
