### ISSUE TITLE
Support for armv8-a ?

### ISSUE THREAD

**Issue by brandex007** [relic-toolkit/relic#198]
I am compiling with -march=armv8-a (Android NDK for 64 bit ARM device) and see the following error:
src/low/arm-asm-254/relic_fp_add_low.s:8:7: error: unknown arch name
.arch armv7-a

Is there support for armv8-a? Thanks

**Comment by dfaranha** [comment]
Not at the moment for the ASM backends. The ASM portions you are seeing were written for 32-bit ARM CPUs.
You can always use the C-based "easy" or GMP backends, however.
