### ISSUE TITLE
Compilation with "ARITH gmp" fails

### ISSUE THREAD

**Issue by a-0-dev** [relic-toolkit/relic#200]
**Setup:** 
RELIC 0.5.0, gmp and gmp-devel version 6.2 libaries installed

**Problem:**
Compilation with ARITH easy (or leaving this option out, defaults to "easy" anyways) works as expected, compilation with ARITH gmp or ARITH gmp-sec yields the following gcc output:
```
In file included from /usr/include/gmp.h:59,
                 from [project]/relic/include/relic_types.h:40,
                 from [project]/relic/include/relic_arch.h:39,
                 from [project]/relic/include/relic.h:81,
                 from [project headers...]
/usr/include/gmp-x86_64.h:2286:33: error: conflicting declaration of C function 'std::ostream& operator<<(std::ostream&, mpq_srcptr)'
 2286 | __GMP_DECLSPEC_XX std::ostream& operator<< (std::ostream &, mpq_srcptr);
      |                                 ^~~~~~~~
/usr/include/gmp-x86_64.h:2285:33: note: previous declaration 'std::ostream& operator<<(std::ostream&, mpz_srcptr)'
 2285 | __GMP_DECLSPEC_XX std::ostream& operator<< (std::ostream &, mpz_srcptr);
      |                                 ^~~~~~~~
/usr/include/gmp-x86_64.h:2287:33: error: conflicting declaration of C function 'std::ostream& operator<<(std::ostream&, mpf_srcptr)'
 2287 | __GMP_DECLSPEC_XX std::ostream& operator<< (std::ostream &, mpf_srcptr);
      |                                 ^~~~~~~~
/usr/include/gmp-x86_64.h:2285:33: note: previous declaration 'std::ostream& operator<<(std::ostream&, mpz_srcptr)'
 2285 | __GMP_DECLSPEC_XX std::ostream& operator<< (std::ostream &, mpz_srcptr);
      |                                 ^~~~~~~~
/usr/include/gmp-x86_64.h:2289:33: error: conflicting declaration of C function 'std::istream& operator>>(std::istream&, mpq_ptr)'
 2289 | __GMP_DECLSPEC_XX std::istream& operator>> (std::istream &, mpq_ptr);
      |                                 ^~~~~~~~
/usr/include/gmp-x86_64.h:2288:33: note: previous declaration 'std::istream& operator>>(std::istream&, mpz_ptr)'
 2288 | __GMP_DECLSPEC_XX std::istream& operator>> (std::istream &, mpz_ptr);
      |                                 ^~~~~~~~
/usr/include/gmp-x86_64.h:2290:33: error: conflicting declaration of C function 'std::istream& operator>>(std::istream&, mpf_ptr)'
 2290 | __GMP_DECLSPEC_XX std::istream& operator>> (std::istream &, mpf_ptr);
      |                                 ^~~~~~~~
/usr/include/gmp-x86_64.h:2288:33: note: previous declaration 'std::istream& operator>>(std::istream&, mpz_ptr)'
 2288 | __GMP_DECLSPEC_XX std::istream& operator>> (std::istream &, mpz_ptr);
```

It seems more like a GMP problem to me, however I assume it's rather some missing build parameter or so. I do not suspect an issue caused by other dependencies as the error seems to be occur within this one header gmp-x86_64.h only.

**Proposed solution:**
(1) In case additional build parameters need to be set, mention those in the  "Building" section of the documentation or include them in the RELIC make files
(2) In case this is solely a GMP issue I'm happy to forward this issue to the GMP project

In case you suspect an error on my side, I hope you can point me in some direction how to solve it. This is very much possible, as this is my first time using RELIC and I am not yet professional-level with C++ either.

**Comment by dfaranha** [comment]
This does not look like a RELIC issue, but problems with your GMP installation (and its header files).

**Comment by a-0-dev** [comment]
Together with the GMP people, I found the solution for this, not sure whether that's something that should be fixed within RELIC.

GMP may not be included as 
```
extern "C" {
#include <gmp.h>
}
```
However, that is exactly what happens when including RELIC as `extern "C"`. So including RELIC as

```
#include <gmp.h>
extern "C" {
#include <relic.h>
}
```
fixes the issue. That is not a major problem for RELIC from a usability standpoint, in case this is a necessary fix for all platforms/installations you may still consider fixing this if you like.

Anyways, thank you for your quick reply and support!

**Comment by dfaranha** [comment]
So GMP has C++ headers already and RELIC does not. :)

Thanks for the notification!
