### ISSUE TITLE
ECIES 160bit

### ISSUE THREAD

**Issue by xATI-researcher** [relic-toolkit/relic#201]
Can ECIES be used by having the settings EC_CUR = PRIME, FP_PRIME 160? I was trying to test this in an Linux environment and I was unable to get a successful ecies_encryption by running the benchmark bench_cp. Are there other settings necessary?

**Comment by dfaranha** [comment]
I just pushed a commit that allows ECIES to be used with SECG-160, SHA256 and AES128. Please let me know if that is sufficient. :)

**Comment by xATI-researcher** [comment]
Thank you for the update :). I tested and it is working now with 160 bit and also with 192bit. 👍 I have one question related to the implementation of ECIES. Is the implementation done according to SECG SEC-1 or to other standards?

**Comment by dfaranha** [comment]
At the time I tried making it compatible with BouncyCastle because I needed interop with them. I don´t remember what standard they are targeting. However, ECIES is an standardization MESS and there are many variants around.
