### ISSUE TITLE
Other way to construct towered extension fields

### ISSUE THREAD

**Issue by luozejiaqun** [relic-toolkit/relic#203]
Is it possible to construct towered extension fields in another way? For example, fp12 now is constructed from 1-2-6 -12, but fp12 can also be constructed from 1-2-4-12. So, is there any reason why the extension fields are constructed the currrent way? And is it possible to support other towered extension filelds?

**Comment by dfaranha** [comment]
The current fields are constructed such that the fastest formulas for multiplication/squaring are obtained. If you look at squarings, you will see that we switch from 1-2-6-12 to 1-2-4-12 for efficiency.
