### ISSUE TITLE
Inconsistent `bn_read_bin` and zero when `ALLOCATION != DYNAMIC`

### ISSUE THREAD

**Issue by huitseeker** [relic-toolkit/relic#204]
In `ALLOC=AUTO` at least, reading `bn_zero` (e.g. the zero scalar) from bytes used to look like:
- initialize a slice of the correct length to zeros,
- pass it to `bn_read_bin`,
- enjoy having all functions (`bn_is_zero`, `bn_cmp_dig` with 0, `bn_cmp` with `bn_zero(x)`) interpret this as zero.

After 16f3c55b055117e1e4cc82160675e2a778a2ed6e, that's no longer true. The `used`-trimming & zero-reset logic present in `bn_trim` is made conditional on having a large enough `alloc`. Since `bn_grow` does not grow the value of `alloc` under `ALLOC != DYNAMIC`, that condition is never met.

As a consequence, whereas before 16f3c55b055117e1e4cc82160675e2a778a2ed6e, the `bn_read_bin` of a zero-slice had a `used` member equal to 1 (just like `bn_zero`!), but after that commit, the `used` value in question is now the length of the slice divided by the word size (i.e. 4 for a 32-byte input slice on 64-bits).

**Comment by dfaranha** [comment]
...and the change was committed/pushed under an innocent-looking commit message. Thanks for reporting! :)

One thing I don't understand is why `used` would not be at most `alloc` (enabling the trimming) if the input buffer is not too large. In other words, do you have offending code?

**Comment by huitseeker** [comment]
@dfaranha [This commit](https://github.com/onflow/flow-go/pull/846/commits/c4fbb857ba0811c6c2fcf9a21746a124edecb1a9) piggy-backs on a different code base, but should be simple enough to make the example clear.

**Comment by dfaranha** [comment]
You need to `bn_new()`or `bn_make()` that `bn_t` to initialize `alloc`.

**Comment by huitseeker** [comment]
Yep, that'd do it. Should we close the issue, since I'm skipping an initializer?
