### ISSUE TITLE
B12_P381 ERROR in ep_param_set()

### ISSUE THREAD

**Issue by chenxin1996** [relic-toolkit/relic#217]
Hello, when I use ep_param_set(B12_P381), I get the following error. What is the reason for this?

ERROR in ep_param_set() at /home/chenxin/Desktop/relic-relic-toolkit-0.5.0/src/ep/relic_ep_param.c,851: invalid value passed as input.
	CAUGHT in ep_param_set() at /home/chenxin/Desktop/relic-relic-toolkit-0.5.0/src/ep/relic_ep_param.c,888.

**Comment by dfaranha** [comment]
Have you configured the library for 381-bit prime fields?
The preset folder has everything you need in that regard.

**Comment by dfaranha** [comment]
Additionally, see https://github.com/relic-toolkit/relic/wiki/Building

**Comment by chenxin1996** [comment]
When I execute ./gmp-pbc-bls381.sh under the preset file, it will appear:

CMake Warning:
  No source or binary directory provided.  Both will be assumed to be the
  same as the current working directory, but note that this warning will
  become a fatal error in future CMake releases.
CMake Error: The source directory "/home/chenxin/Desktop/relic-0.5.0/preset" does not appear to contain CMakeLists.txt.
Specify --help for usage, or press the help button on the CMake GUI.

Is the command I entered incorrect?

**Comment by dfaranha** [comment]
Please follow the Building instructions in the wiki page linked above.

**Comment by chenxin1996** [comment]
When I execute../relic-0.5.0/preset/gmp-pbc-bls381 ../relic-0.5.0 under ~/Desktop/relic-0.5.0/relic-target, it will appear:

bash: ../relic-0.5.0/preset/gmp-pbc-bls381: No such file or directory

I am sure that I followed the build instructions on the wiki page exactly. I am a beginner in cryptographic programming, maybe the question I asked was a bit stupid but it bothered me.

**Comment by dfaranha** [comment]
You should run `../relic-0.5.0/preset/gmp-pbc-bls381.sh ../` under `~/Desktop/relic-0.5.0/relic-target`.

**Comment by chenxin1996** [comment]
Thank you very much for your specific operation. But I have left my workshop to go back to my dormitory to rest, because I am at UTC / GMT + 08:00, it is already late at night. I'll try your suggestion tomorrow. Thank you very much.

**Comment by chenxin1996** [comment]
I got the following error：
bash: ../relic-0.5.0/preset/gmp-pbc-bls381.sh: No such file or directory
But gmp-pbc-bls381 does exist

**Comment by dfaranha** [comment]
Corrected the paths above.

**Comment by chenxin1996** [comment]
Now it can run normally, thank you very much！
