### ISSUE TITLE
BENCH: pp_exp_k12 hangs

### ISSUE THREAD

**Issue by YWRtaW4** [relic-toolkit/relic#230]
I ran `src/presets/gmp-pbc-bn254.sh` and `make`, then ran `bin/bench_pp`, the bench test ran well until `pp_exp_12`. Then I added `DBENCH=20` into `src/presets/gmp-pbc-bn254.sh` but the hanging situation is the same.

**Comment by dfaranha** [comment]
Thanks for notifying!

I missed up the preset by pushing a debugging configuration. Can you test again with the latest version?

**Comment by YWRtaW4** [comment]
I tested it again and it's working as expected. Thank you for your reply and work!
