### ISSUE TITLE
Does relic support the symmetric pairing?

### ISSUE THREAD

**Issue by YWRtaW4** [relic-toolkit/relic#241]
If I want to implement a protocol with symmetric pairing at the AES-80 security level, I would like to know how to achieve this with relic. Thanks.

**Comment by YWRtaW4** [comment]
I run e(a*P,Q)*e(b*P,Q) with pp_map_weilp_k2() under BN_P256 curve, and it turns out that the result is not equal to e(a*P+b*P,Q) which should be equal according to the bilinearity of pairings.

And the cmake that I use is `cmake -DWSIZE=64 -DCHECK=off -DVERBS=off -DARITH=gmp -DFP_PRIME=256 -DFP_METHD="INTEG;INTEG;INTEG;MONTY;LOWER;LOWER;SLIDE" -DCFLAGS="-O3 -funroll-loops -fomit-frame-pointer -finline-small-functions -march=native -mtune=native" -DFP_PMERS=off -DFP_QNRES=on -DMD_METHD=SH256 -DEP_ENDOM=on -DEP_PLAIN=off -DFPX_METHD="INTEG;INTEG;LAZYR" -DPP_METHD="LAZYR;WEILP" $1`

**Comment by YWRtaW4** [comment]
I've fixed my problem.

**Comment by dfaranha** [comment]
Hi, I'm late to the game, but you should use `FP_PRIME=1536` to access the Type-1 pairing implementation contained in RELIC.

**Comment by YWRtaW4** [comment]
Yes, I've done as you said and got the desired result. Thank you for your reply! And RELIC is fantanstic! :)
