### ISSUE TITLE
How to see which curve is used in bench_cp

### ISSUE THREAD

**Issue by XinwenXiang** [relic-toolkit/relic#243]
Hello, I'm running bench_cp to make some comparison.
But there is no curve innformation in  this bench_cp, how can i find it?
![image](https://user-images.githubusercontent.com/33709586/180424595-1999e656-b9e6-413c-ae2c-cd60424d65de.png)
Best Regards.

**Comment by dfaranha** [comment]
You can run `bench_ec` or `bench_pc` to find out which curve is being used.

**Comment by XinwenXiang** [comment]
thanks!
