### ISSUE TITLE
Cannot you move this under line 227 to increase performance?

### ISSUE THREAD

**Issue by mlvl36667** [relic-toolkit/relic#245]
https://github.com/relic-toolkit/relic/blob/234a0347f79f86152e91920086310e9d9e676fa9/src/tmpl/relic_tmpl_map.h#L220

If I am not mistaken we don't need these quantities when the x coordinate calculated above happens to be a quadratic residue and we can take the square root to calculate y.

**Comment by dfaranha** [comment]
Looks like it, even though it's just one field multiplication. :)

**Comment by mlvl36667** [comment]
Also, what about using y = g(x)^{(p+1)/4} instead of taking the square root for BLS12-381? Which approach is better?

**Comment by dfaranha** [comment]
That's exactly what square root computes in case of the BLS12 prime. :)

For faster hashing, there should be an update in a few weeks implementing https://eprint.iacr.org/2022/759, so stay tuned!

**Comment by mlvl36667** [comment]
I know that they're equivalent, I'm just wondering which one is more expensive to calculate. Thank you for the article, I'll have a look.

**Comment by dfaranha** [comment]
Sorry if my comment was not clear. In RELIC, `fp_srt() ` extracts the square root exactly by computing the exponentiation.

**Comment by mlvl36667** [comment]
Thanks. Now I see. I should have look at it myself though...

**Comment by mlvl36667** [comment]
There is one more thing I don't understand. In "Fast and simple constant-time hashing to the BLS12-381 elliptic curve" the second square root is avoided by calculating y as t^3*alpha, but in your implementation you calculate two square roots. Can you explain me the reason?

**Comment by dfaranha** [comment]
We did not have a fast squaredness test at the time, but now we have a pretty good one (upcoming paper on CCS'23 -- built upon ideas from https://eprint.iacr.org/2021/1271).

There is quite a bit of movement happening in the hashing part, including a new function and an attempt to make this one faster/constant-time: 5bd2b8b7b555533a4b1e6cea62bb45c57b898b5d

**Comment by mlvl36667** [comment]
Sounds good. I'll have a look at it. Thank you for clarifying.

**Comment by dfaranha** [comment]
I just merged a large patch with many new hash-to-curve algorithms for the various cases. Some polish is still pending for automatic selection, but the basics are there.
