### ISSUE TITLE
ECIES on Atmega2560

### ISSUE THREAD

**Issue by xATI-researcher** [relic-toolkit/relic#247]
I have tried to build (in a Linux environment) the last version of relic toolkit in order to deployed it on an Atmega2560 board but I always get segmentation fault when running on the actual device. I have use as an example the post from here https://github.com/ms-s/relic-configurations. Are low memory devices supported for the newer versions of relic toolkit and it is possible to actually use the ECIES on them?

**Comment by dfaranha** [comment]
It should be possible, but its many years since we tried for the last time. What configuration do you have in your board? How much RAM memory in each segment?

**Comment by xATI-researcher** [comment]
This issue can be closed. In the end I have used an older version which supported low memory configuration for ECIES.
