### ISSUE TITLE
CHECK=off keeps setjmp.h dependency

### ISSUE THREAD

**Issue by fominok** [relic-toolkit/relic#248]
Hello,
As far as I understood, `CHECK=off` should turn off try/catch capabilities that require `setjmp/longjmp` usage, but it still depends on it as `#include` is unconditional.

This exact header is a problem that prevents Relic to compile to such targets as `wasm32-unknown-unknown` and `wasm32-wasi`.

**Comment by dfaranha** [comment]
True! Can you send a simple PR making the inclusion conditional as well? Thanks!

**Comment by fominok** [comment]
I made a PR, cannot successfully compile though, but other issues are unrelated

**Comment by dfaranha** [comment]
Merged!
