### ISSUE TITLE
Relic Error

### ISSUE THREAD

**Issue by j081010** [relic-toolkit/relic#25]
Hi，
I had a problem when I try to cmake relic-master. The problem as follows: 
  CMake Error at src/CMakeList.txt:9 (string):
       string no output  variable specified
 -- Could not find Doxygen (missing: DOXYGEN_EXECUTABLE)
 -- Configuring incomplete, error occurred!

Thanks!

**Comment by dfaranha** [comment]
Hi,

You can install doxygen to get rid of one of the problems, but I need more information about the first. What commands did you run when trying to compile the library?

Thanks!

**Comment by j081010** [comment]
Hi,
I used the command  "cmake . "
I want to know whether the library can be used in the contiki operating system. My envrionment is Instant-contiki 2.7

Thanks!

**Comment by dfaranha** [comment]
Notice you should build the library in a separate folder and pass the path to the source as the CMake argument. Our discussion group has some people who could make RELIC work with Contiki, so perhaps you should ask there?

**Comment by j081010** [comment]
Whether the library must be used in a 64 bit system？ 

Thank！

**Comment by j081010** [comment]
And how can I contact with them if I want to ask somthing about make RELIC work with Contiki?

Thanks!

**Comment by dfaranha** [comment]
Please post to http://groups.google.com/group/relic-discuss
