### ISSUE TITLE
Is it possible to implement DH Key Exchange X25519 with Relic?

### ISSUE THREAD

**Issue by oliviervibe** [relic-toolkit/relic#252]
This is not an issue, but I don't know where to ask that question!

I would like to implement a ECDH with the Curve25519 like done in TLS 1.3. (I would like avoiding OpenSSL as I only need that!)

With Relic configured for OATEP pairing, is it possible to configure ECDH for X25519? I'd appreciate if someone could show me how, if it is possible!

Thanks

**Comment by dfaranha** [comment]
RELIC is a research library probably filled with more bugs and vulnerabilities than OpenSSL. You should look for a stand-alone implementation of X25519, of which there are many. For example: https://github.com/agl/curve25519-donna
