### ISSUE TITLE
bench_rand.c not compiling with RAND=CALL

### ISSUE THREAD

**Issue by jgdumas** [relic-toolkit/relic#263]
In file [bench/bench_rand.c](https://github.com/relic-toolkit/relic/blob/main/bench/bench_rand.c)

65:		rand_bytes(buffer, k);

error: ‘k’ was not declared in this scope

Replace `k`, by `sizeof(buffer)` ?

**Comment by dfaranha** [comment]
Fixed with 70dc2089d13b10b8c458dc323baf78bb28689486, thanks for notifying!
