### ISSUE TITLE
BLS signatures with point compression

### ISSUE THREAD

**Issue by xATI-researcher** [relic-toolkit/relic#272]
Hello. I have tested BLS signatures with the curve B12-P381 for research purposes and I have noticed that the output signature size is 96 bytes having the signature in the G1 group. Is there a way to use the point compression option in order to reduce the size of the resulted signature?

**Comment by dfaranha** [comment]
Hi,

It's not visible in the API for BLS signatures, but you can request a compressed G1 element when serializing it to a byte buffer using the function `g1_write_bin`. There is a specific flag there for compression.

Hope it helps!

**Comment by xATI-researcher** [comment]
Hello. It works using g1_write_bin and g1_read_bin for compressing and  deserializing a G1 element. Thank you very much for the fast answer.
