### ISSUE TITLE
Want to use BN_254 curve

### ISSUE THREAD

**Issue by anujamodi0107** [relic-toolkit/relic#274]
Hello,
I want to use the BN_254 curve in my project. However, I cannot figure out how to use it in C code. When I write these two lines, it gives me an error.

The line: ep_param_set(254);
		ep_param_print();
The error: invalid value passed as input.
	CAUGHT in ep_param_set()

Can anyone please tell me the correct way to use it?

Thanks.

**Comment by dfaranha** [comment]
You can use the preset `x64-pbc-bn254.sh` to configure everything for you. Hope it helps!
