### ISSUE TITLE
cmake error the target not found

### ISSUE THREAD

**Issue by mialuyao** [relic-toolkit/relic#281]
Hello
I have installed relic and pass all test project. 
`librelic_s.a` and `librelic.so` at `/usr/local/lib`
Head files at `/usr/local/include/relic/`
When I cmake my project, it always show cmake error, but I have set the `INCLUDE_DIRS` and `LIBRARIES PATH` at CMakeLists.txt
```
CMake Error at CMakeLists.txt:16 (add_executable):
  Target "my_prohect" links to target "RELIC::relic" but the target
  was not found.  Perhaps a find_package() call is missing for an IMPORTED
  target, or an ALIAS target is missing?
```
CMakeLists.txt as below
``` 
set(RLC_INCLUDE_DIRS "/usr/local/include/relic")
set(RLC_LIBRARIES "/usr/local/lib/librelic_s.a")
....
target_link_libraries(.... ${RLC_LIBRARIES})
```
Thank you!

**Comment by dfaranha** [comment]
Closing due to no answer.
