### ISSUE TITLE
test_cp.c: cp_rsa_sig_basic() failure

### ISSUE THREAD

**Issue by Zopieux** [relic-toolkit/relic#29]
### Configuration/preset

```bash
cmake -DARCH=X86 -DWORD=32 -DBENCH=1 "-DBN_METHD=BASIC;BASIC;BASIC;BASIC;BASIC;BASIC" -DCHECK=OFF -DCOLOR=OFF -DCOMP="-O0 -g" -DDOCUM=OFF -DEP_ENDOM=OFF "-DFP_METHD=BASIC;BASIC;BASIC;BASIC;BASIC;BASIC" -DEP_DEPTH=3 -DMD_MAP=SH256 -DFP_PMERS=ON -DSEED=ZERO -DSHLIB=OFF -DSTRIP=ON -DTESTS=1 -DTIMER=CYCLE -DVERBS=OFF -DFP_PRIME=256 -DBN_PRECI=256 -DMD_METHD=SH256 "-DWITH=FP;EP;EC;DV;CP;MD;BN;BC" -DCP_ECDSA=BASIC -DEC_ENDOM=OFF -DCP_METHD=PRIME -DEC_METHD=PRIME $1
```

Also tested (same issue) with `CP_RSA` = `BASIC` and `QUICK`, and `CP_RSAPD` = `BASIC`, `PCKS1` and `PCKS2`.

### Issue

Platform: Linux 3.13.0-62-generic #102-Ubuntu SMP Tue Aug 11 14:28:35 UTC 2015 i686 GNU/Linux

All tests and benches are fine, except `test_cp`:

```c
// in main() at test_cp.c:1128
// in rsa() at test_cp.c:100
// in cp_rsa_sig_basic() at relic_cp_rsa.c:946
int cp_rsa_sig_basic(/* snip */) {
	/* snip */
	size = bn_size_bin(prv->n);
	// size = 32
	if (pad_len > (size - RSA_PAD_LEN)) {
	// pad_len = 32, RSA_PAD_LEN = 11, thus 32 > 32 - 11 indeed
		return STS_ERR;
	}
```

Is it a configuration issue?

**Comment by dfaranha** [comment]
Yes! By signing SHA256 hashes, there is no room left for any padding. I suggest you increase the BN_PRECI config variable.

**Comment by Zopieux** [comment]
Thanks, increased to 512, works fine.

**Comment by dfaranha** [comment]
Please note that RSA-512 is not secure by any means, although I suspect you are just trying to make the tests go through. :)

**Comment by Zopieux** [comment]
Indeed :-)
