### ISSUE TITLE
Error generating lib file

### ISSUE THREAD

**Issue by Salterwater23** [relic-toolkit/relic#293]
I am using cmake 3.29,vs2022
cmake ... / -G "NMake Makefiles"
The following error occurs

D:\evn\relic-main\Build>cmake ../ -G "NMake Makefiles"
CMake Warning (dev) in CMakeLists.txt:
  No project() command is present.  The top-level CMakeLists.txt file must
  contain a literal, direct call to the project() command.  Add a line of
  code such as

    project(ProjectName)

  near the top of the file, but after cmake_minimum_required().

  CMake is pretending there is a "project(Project)" command on the first
  line.
This warning is for project developers.  Use -Wno-dev to suppress it.

**Comment by Salterwater23** [comment]
Problems encountered now
D:\evn\relic-main\Build>nmake

Microsoft (R) 程序维护实用工具 14.39.33523.0 版
版权所有 (C) Microsoft Corporation。  保留所有权利。

No lib file is generated

**Comment by Salterwater23** [comment]
Problems encountered now
D:\evn\relic-main\Build>nmake

Microsoft (R) 程序维护实用工具 14.39.33523.0 版
版权所有 (C) Microsoft Corporation。  保留所有权利。

No lib file is generated

**Comment by dfaranha** [comment]
Hi

I don't understand the problem. The `CMakeLists.txt` at the root of the RELIC folder has such a `project` line.

Can you please double-check your paths?

**Comment by dfaranha** [comment]
From your other issue, I believe this has been solved.
