### ISSUE TITLE
ep_curve_set_map()

### ISSUE THREAD

**Issue by 121TheShuDynasty** [relic-toolkit/relic#295]
I installed the library by running 'cmake ..; make;', but when using 'ep_param_set(SM2_P256)', I encountered an ERROR in ep_curve_set_map() at /home/yang/relic/relic-main/src/ep/relic_ep_curve.c, line 180: invalid value passed as input. CAUGHT in ep_curve_set_map() at /home/yang/relic/relic-main/src/ep/relic_ep_curve.c, line 185. CAUGHT in ep_param_set() at /home/yang/relic/relic-main/src/ep/relic_ep_param.c, line 1372.

**Comment by dfaranha** [comment]
Hi,

Support to the SM2-P256 curve is not complete and may be buggy. I suggest picking another curve for your implementation and experiments.

**Comment by dfaranha** [comment]
I need more information to be able to help. What installation process did you use?

**Comment by dfaranha** [comment]
Does you code work with NIST-P256?

**Comment by dfaranha** [comment]
You cannot pass NIST-P192 because the library by default is built for 256-bit fields. You need to reconfigure+recompile for that.

I will continue looking into the other error.

**Comment by 121TheShuDynasty** [comment]
I understand that I cannot use NIST-P192, but I still don't know how to use SM2-P256. I'm new to this area, so please forgive my ignorance.

**Comment by dfaranha** [comment]
I just tried the code below with the latest version and I saw no errors:

```
#include "relic.h"

int main() {
        ep_t p;

        core_init();
        ep_param_set(NIST_P256);
        ep_param_print();
        ep_rand(p);
        ep_print(p);

        ep_param_set(SM2_P256);
        ep_param_print();
        ep_rand(p);
        ep_print(p);
        core_clean();
        return 0;
}
```

**Comment by 121TheShuDynasty** [comment]
![微信截图_20240424014602](https://github.com/relic-toolkit/relic/assets/97268594/ccfc6588-862b-4947-b53c-26244cdfe7eb)
I downloaded the project again for configuration, ran your program, and encountered this error. Is it possibly due to the system?

**Comment by dfaranha** [comment]
I'm sorry, I had pushed the fix to another branch. Not it's back on `main`.

Can you please try again?

**Comment by 121TheShuDynasty** [comment]
The SM2_P256 curve is fine, thank you, but other P256 curves such as SM9_P256, BSI_P256, etc., are causing segmentation faults, and the core has been dumped.

**Comment by dfaranha** [comment]
BSI_P256 should be fixed now as well.
