### ISSUE TITLE
Error on sha256

### ISSUE THREAD

**Issue by TheYangCode** [relic-toolkit/relic#299]
Hello, I used the following code:
```
void printHex(const uint8_t *str) {
    while (*str) {
        printf("%02X", (unsigned char)*str);
        str++;
    }
    printf("\n");
}

uint8_t m[RLC_MD_LEN_SH256] = "helloworld";
uint8_t m_hash[RLC_MD_LEN_SH256];
size_t m_size = sizeof(m) / sizeof(uint8_t);
md_map_sh256(m_hash, m, m_size);
printHex(m_hash);
```
Hash result：07116C344512DC38D960BBFAF305B0D1020484C77DD3EFE6E06C38066A92D495C0099A54FE7F
But the true sha256 hash result is ：936a185caaa266bb9cbe981e9e05cb78cd732b0b3280eb944412bb6f8f8f07af

I want to know why?Thank you.

**Comment by dfaranha** [comment]
Value `m_size` should be the length of `m`, not its size.

**Comment by TheYangCode** [comment]
```
    bn_t output
    uint8_t output_hash[RLC_MD_LEN_SH256];
    md_map_sh256(output_hash, input, input_len);
    bn_read_bin(output, output_hash, RLC_MD_LEN_SH256);
    bn_mod_basic(output, output, q);
    
```

**Comment by dfaranha** [comment]
You should initialize `output` with `bn_new()` and finalize it too. Have you initialized `q` as well with some group order?

**Comment by TheYangCode** [comment]
Thank you for your answer. My question has been resolved

**Comment by TheYangCode** [comment]
Another question, does the current Relic library support Merkle tree generation calculation?

**Comment by dfaranha** [comment]
Nope, not implemented!
