### ISSUE TITLE
Regarding the optimization method for `g1_mul_sim_lot()`

### ISSUE THREAD

**Issue by TheYangCode** [relic-toolkit/relic#306]
Hello, sorry to bother you. I implemented my research scheme using the relic library and found that `g1_mul_sim_lot()` improved efficiency by nearly half. However, I did not see any explanation regarding the optimization method in the code. It seems to have used the GLV decomposition method (I used ChatGPT). However, I am not sure, so I would like to ask what specific optimization method was used. Could you provide the full name and references? I want to explain the reasons for the improvement in efficiency in my research scheme.

**Comment by dfaranha** [comment]
It implements Pippenger's algorithm!

**Comment by TheYangCode** [comment]
Thank you for your response
