### ISSUE TITLE
Is there a way to build the library on Android?

### ISSUE THREAD

**Issue by YangRongAtGit** [relic-toolkit/relic#32]
Hello,

As the topic asked. The target I am working on is to use the library on a specific android version: 5.1.1_r30. The best tool I could find to convert CMake to android project is: https://github.com/taka-no-me/android-cmake

There are lots of errors when I run the script. I fixed some but still not able to generate libraries files successfully. 

Before I keep trying to fix those errors. I would like to ask: Is there a better way to use the relic library on an android device?

---

**Environment :**
Ubuntu 16.04
gcc / g++ : 4.9.3
AOSP: 5.1.1_r30
Android API level: 22
NDK: android-ndk-r12b
cmake version 3.5.1
GNU Make 4.1 Built for x86_64-pc-linux-gnu

---

Cheers,

Rong

**Comment by conradoplg** [comment]
I did it once. The easier way is to [build a standalone toolchain](https://developer.android.com/ndk/guides/standalone_toolchain.html). With the CC variable exported as described there, just call cmake and make according the RELIC's instructions. This will result in a .a library which can be called by your Android application (you will still need to write the necessary JNI Java glue to call it)

**Comment by YangRongAtGit** [comment]
Hi conradoplg, thanks for your reply, I tried to follow the google guild. I am able to call `<relic_root>\build\cmake ..` to config the project. But when I call `<relic_root>\build\make` I got following errors:

```
arm-linux-androideabi-gcc-4.9.x: error: unrecognized command line option '-m64'
src/CMakeFiles/relic.dir/build.make:62: recipe for target 'src/CMakeFiles/relic.dir/relic_err.c.o' failed
make[2]: *** [src/CMakeFiles/relic.dir/relic_err.c.o] Error 1
CMakeFiles/Makefile2:120: recipe for target 'src/CMakeFiles/relic.dir/all' failed
make[1]: *** [src/CMakeFiles/relic.dir/all] Error 2
Makefile:138: recipe for target 'all' failed
make: *** [all] Error 2
```

Did you have the same problem when you build the library for android?

**Comment by conradoplg** [comment]
You need to set the architecture for RELIC with `cmake -DARCH=arm -DWORD=32 .` before running `make`.

**Comment by dfaranha** [comment]
The present in https://github.com/relic-toolkit/relic/blob/master/preset/armdroid-pbc-128.sh may help you too.

**Comment by YangRongAtGit** [comment]
Thanks for your suggestions. I modified the script that dfaranha suggested (since I am targeting different api level). It compiled successfully.

```
DROID_API_LV=android-22
#export NDK=/opt/android-ndk
#export NDK=$ANDROID_NDK
export NDK=<ndk_path>
SYSROOT=$NDK/platforms/$DROID_API_LV/arch-arm

COMPILER_PREFIX=$NDK/toolchains/arm-linux-androideabi-4.9/prebuilt/linux-x86_64/bin/arm-linux-androideabi-

export CC="${COMPILER_PREFIX}gcc  --sysroot=$SYSROOT"
export CXX="${COMPILER_PREFIX}g++  --sysroot=$SYSROOT"
export LD= "${COMPILER_PREFIX}ld  --sysroot=$SYSROOT"
export CPP="${COMPILER_PREFIX}cpp  --sysroot=$SYSROOT"
export AS="${COMPILER_PREFIX}as  --sysroot=$SYSROOT"
export OBJCOPY="${COMPILER_PREFIX}objcopy  --sysroot=$SYSROOT"
export OBJDUMP="${COMPILER_PREFIX}objdump  --sysroot=$SYSROOT"
export STRIP="${COMPILER_PREFIX}strip  --sysroot=$SYSROOT"
export RANLIB="${COMPILER_PREFIX}ranlib  --sysroot=$SYSROOT"
export CCLD="${COMPILER_PREFIX}gcc  --sysroot=$SYSROOT"
export AR="${COMPILER_PREFIX}ar  --sysroot=$SYSROOT"

cmake -DWITH="DV;BN;MD;FP;EP;FPX;EPX;PP;PC" -DCHECK=off -DARITH=arm-asm-254 -DARCH=ARM -DCOLOR=off -DOPSYS=DROID -DFP_PRIME=254 -DFP_QNRES=on -DFP_METHD="INTEG;INTEG;INTEG;MONTY;EXGCD;SLIDE" -DFPX_METHD="INTEG;INTEG;LAZYR" -DPP_METHD="LAZYR;OATEP" -DCOMP="-O3 -funroll-loops -fomit-frame-pointer -I$NDK/platforms/$DROID_API_LV/arch-arm/usr/include" -DLINK="-L/opt/android-ndk/platforms/$DROID_API_LV/arch-arm/usr/lib/ -llog" -DTIMER=HREAL -DWORD=32 -DSTLIB=on -DSHLIB=off $1
```

**Comment by YangRongAtGit** [comment]
To include `Cryptographic protocols` module. The parameter CP are required in `WITH`. <br>
Instead of using 
`-DWITH="DV;BN;MD;FP;EP;FPX;EPX;PP;PC"`
`-DWITH="DV;BN;MD;FP;EP;FPX;EPX;PP;PC;CP"` is required

**Comment by dfaranha** [comment]
True, I now modified the official present to include the CP module. :)
