### ISSUE TITLE
Fails to compile with clang when ALLOC != AUTO

### ISSUE THREAD

**Issue by sietseringers** [relic-toolkit/relic#35]
When using clang (the default on macOS) instead of gcc to compile, and when ALLOC is not AUTO but any of the other options, compilation errors occur. For example, when using STACK I get these:

```
relic/src/pp/relic_pp_map.c:107:2: error: array type 'ep_t [m]'
      is not assignable
        ep_null(_q);
        ^       ~~
relic/src/pp/relic_pp_map.c:139:3: error: subscripted value is
      not an array, pointer, or vector
                fp2_free(m);
                ^~~~~~~~~~~
relic/src/pp/relic_pp_map.c:139:3: error: subscripted value is
      not an array, pointer, or vector
                fp2_free(m);
                ^~~~~~~~~~~
relic/src/pp/relic_pp_map.c:140:3: error: member reference base
      type 'ep_t' (aka 'ep_st *') is not a structure or union
                ep_free(_q);
                ^~~~~~~~~~~
relic/src/pp/relic_pp_map.c:140:3: error: member reference base
      type 'ep_t' (aka 'ep_st *') is not a structure or union
                ep_free(_q);
                ^~~~~~~~~~~
relic/src/pp/relic_pp_map.c:140:3: error: member reference base
      type 'ep_t' (aka 'ep_st *') is not a structure or union
                ep_free(_q);
                ^~~~~~~~~~~
relic/src/pp/relic_pp_map.c:140:3: error: array type 'ep_t [m]'
      is not assignable
                ep_free(_q);
                ^       ~~
```

**Comment by dfaranha** [comment]
Thanks for the report, Sietse!

These issues were rather silly and should be fixed with the latest commits, however, there are still some runtime problems with clang in my local build. I'll try getting our Buildbot to run again to prevent similar issues in the future. 

I will take the opportunity to ask a question about memory allocators. Do you actually need this feature? It's one of the things under consideration for removal to streamline the library interface.

**Comment by sietseringers** [comment]
I don't think so, no. I'm experimenting a little with a JNA wrapper and thought the other allocators might be useful, but it turns out AUTO works fine. So removing the others sounds like a fine fix :innocent:

**Comment by dfaranha** [comment]
Thanks, this will greatly simplify the library interface and error handling. :)
