### ISSUE TITLE
md_hmac(...) uses Variable-length automatic arrays after scope exit

### ISSUE THREAD

**Issue by ladnir** [relic-toolkit/relic#43]
in the function void [md_hmac](https://github.com/relic-toolkit/relic/blob/54781fb6a60781bddaa78217883c73678e902508/src/md/relic_md_hmac.c#L42)(...) in the file relic_md_hmac.c, there is illegal use of Variable-length automatic arrays in that these arrays are allocated in a local _if_ scope and then used outside this scope. 

The C99 standard stated that these arrays are deallocated on the completion of the scope. However, the code copies the pointer into the containing scope and then uses it.

**Comment by dfaranha** [comment]
That is indeed true and should be fixed in the repository now. Can you please check?
Thanks for the notification!
