### ISSUE TITLE
Problem with linking relic functions

### ISSUE THREAD

**Issue by mikispeedy** [relic-toolkit/relic#44]
I'm using TinyOS 2.1.2 with last relic release for my thesis and i have the following issue:
when I compile my project it goes well but when I run the application I get an error referred to relic functions. Dumping the _TOSSIMmodule.so file i found out that relic library doesn't result linked. I checked the MakeFile and I correctly set library path but the problem persists.

**Comment by dfaranha** [comment]
I assume this has been solved already. :)
