### ISSUE TITLE
Insecure generation of random curve points

### ISSUE THREAD

**Issue by rbost** [relic-toolkit/relic#46]
The way random curve points (at least for prime curves) are generated is biased: the following code comes from relic_ep_util.c (lines 82-87).
```c
ep_curve_get_ord(n);

bn_rand(k, BN_POS, bn_bits(n));
bn_mod(k, k, n);

ep_mul_gen(p, k);
```

More precisely, there is a bias in the way k is generated, that can be statistically significant. 
Instead, you should either proceed by rejection sampling, or by randomly generating k with bn_bits(n)+lambda bits, and then reducing mod n. In the latter case, the generation of k will be 2^{-lambda} statistically close to uniform in [0, n-1].

I suggest to replace the code as follows (not tested)
```c
ep_curve_get_ord(n);

bn_rand(k, BN_POS, bn_bits(n)+STAT_DISTANCE);
bn_mod(k, k, n);

ep_mul_gen(p, k);
```
and let STAT_DISTANCE be defined in a configuration file. By default, it should be 30.

**Comment by dfaranha** [comment]
Thanks for the notification!

I have centralized these samplings into bn_rand_mod() and have implemented countermeasures there (both rejection of trivial values and statistical distance).
