### ISSUE TITLE
Is there a way to export specific arithmetics for a specific kind of curve?

### ISSUE THREAD

**Issue by shalec** [relic-toolkit/relic#48]
Hey,
I'm interested in implementing KSS-16 and the optimal Ate-pairing on Cortex M4 and I would like build this up on a well running lib. So I would like to export the whole arithmetic for KSS 16 curves and declare the latest suggested key sizes from [1]. 

In the end I'm only interested in some benchmarks. 

[1] https://eprint.iacr.org/2017/334

**Comment by dfaranha** [comment]
Closed due to inactivity. In the meanwhile, KSS-16 curves were also properly implemented in the library.
