### ISSUE TITLE
naming collision for ZERO

### ISSUE THREAD

**Issue by wangxiao1254** [relic-toolkit/relic#50]
ZERO is defined as 6 in
https://github.com/relic-toolkit/relic/blob/master/include/relic_conf.h.in#L687

which can collide with other code easily, that defines ZERO as 0 :)

Would be good to change to RELIC_ZERO for defines in that file (and maybe other variables too).

**Comment by dfaranha** [comment]
I simplified this by making ZERO to be the behavior when the configuration symbol is not defined, avoiding possible conflicts.
