### ISSUE TITLE
Save cycles while copy elements

### ISSUE THREAD

**Issue by shalec** [relic-toolkit/relic#56]
I'm actually on my master thesis and discovered a small but signifanct difference in doing:
`void fp_copy(fp_t c, const fp_t a) {
	for (int i = 0; i < FP_DIGS; i++) {
		c[i] = a[i];
	}
}`

and using memcpy. 

I'm implementing the KSS-16 arithmetics on an ARM Cortex M4 and discovered, that this way uses 1.5 times of the cycle count of memcpy. Another fact I found out, defining a macro for memcpy uses 38 instead of 30 cycles by a word size of 11*4 bytes. Defining a function that uses memcpy needs 60 cycles. 

I don't know if you have mentioned such things before, but this is a hint and could enhance some evaluations on a small amount. (Compiling with arm-none-eabi-gcc and -Ofast.) For me, the best but not fastest method is defining a macro.

**Comment by dfaranha** [comment]
I have unified the copying functions to use dv_copy() and changed the latter to use memcpy() instead. It's now easier to revert the change due to the centralized point.

Function calls are indeed pretty expensive on the Cortex-Ms. :(
