### ISSUE TITLE
On machines, where #MUL = #ADD hybrid karazuba is faster

### ISSUE THREAD

**Issue by shalec** [relic-toolkit/relic#57]
Hey, 

I'm currently developing the optimal Ate pairing on an ARM Cortex M4 processor. On that the used cycles for multiplication and addition of (unsigned) 32-bit integers is equal to one. Therefore, the trade off of multiplication for additions is faster, as long the total count is the lowest. So it turned out for multiplication on $F_p$ the schoolbook method, if you can handle the carry well, is the fastest method. But in tower fields, where the $F_p$ multiplication is used, a hybrid Karazuba gains alot of speed. 

Consider $F_{p^{16}}$, on my measures the 2-iterative Karazuba (two 16 word arrays split into four eight word arrays, which are itselve split into two four word arrays) with a final fall back schoolbook method, (for degree four polynomials) turned out to be the fastest method. 

The only bottleneck is the modular reduction. If you try to use the $F_p$ reduction after every multiplication you lose a lot of performance. The probably best way is to sum up all coefficients and using the reduction afterwards. I guess this could be called something like "lazy reduction".

**Comment by dfaranha** [comment]
Fortunately, the RELIC configuration allows you to select among several of these options. :)
