### ISSUE TITLE
relic calls exit(0) on error

### ISSUE THREAD

**Issue by FiloSottile** [relic-toolkit/relic#59]
On a call to `ep_read_bin`, relic encounters two errors in a row (stopping me from handling/clearing the first, which I think is a bug in and of itself), and then exits with code 0.

```
ERROR in bn_div_rem() at /Users/filippo/src/github.com/FiloSottile/powersoftau/relic/relic/src/bn/relic_bn_div.c,139: invalid value passed as input.
	CAUGHT in fp_prime_conv() at /Users/filippo/src/github.com/FiloSottile/powersoftau/relic/relic/src/fp/relic_fp_prime.c,472.
	CAUGHT in fp_read_bin() at /Users/filippo/src/github.com/FiloSottile/powersoftau/relic/relic/src/fp/relic_fp_util.c,252.

ERROR in bn_div_rem() at /Users/filippo/src/github.com/FiloSottile/powersoftau/relic/relic/src/bn/relic_bn_div.c,139: invalid value passed as input.
	CAUGHT in fp_prime_conv() at /Users/filippo/src/github.com/FiloSottile/powersoftau/relic/relic/src/fp/relic_fp_prime.c,472.
```

**Comment by FiloSottile** [comment]
Patching this like to `exit(1)` makes the program exit with a non-success code.

https://github.com/relic-toolkit/relic/blob/5784facac01fc27fd9960cb8a9065b0a60b140ff/include/relic_err.h#L207

**Comment by FiloSottile** [comment]
The cause is that `E` comes from `THROW(ERR_CAUGHT)`, but I'm pretty confused as to why ERR_CAUGHT is 0, since it causes an exit anyway.

**Comment by dfaranha** [comment]
I soon hope to throw most of the error-handling mechanism away, but I fixed this by renaming the error codes accordingly in 5e1319e3c82a1f722573c53e877e008e04f9be2c.
