### ISSUE TITLE
Crashing whenever calling ec_read_bin()

### ISSUE THREAD

**Issue by bernardowilson** [relic-toolkit/relic#62]
Whenever calling the library code to read an ec_t from an array previously filled with ec_write_bin(), the library crashes with a SEGFAULT.

The code calls which can cause a crash are as follows:
 
```c
        ec_t curve;
	ec_null(curve);
	ec_new(curve);

	int size = ec_size_bin(curve, 0);
	uint8_t* curveArr = malloc(size * sizeof(uint8_t));

	ec_write_bin(curveArr, size, curve, 0);

	ec_t curveCopy;
	ec_null(curveCopy);
	ec_new(curveCopy);

	ec_read_bin(curveCopy, curveArr, size);
```
My system information is: 

Linux hostname.tld 4.4.0-104-generic #127-Ubuntu SMP Mon Dec 11 12:16:42 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux

gcc (Ubuntu 5.4.0-6ubuntu1~16.04.5) 5.4.0 20160609
Copyright (C) 2015 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

libgmp-dev (2:6.1.0+dfsg-2) from ubuntu repos.

If you need any more information to help diagnose this issue, please ask: I'll be happy to provide it!

**Comment by conradoplg** [comment]
I wasn't able to reproduce the issue with the default configuration. How did you configure the library?

**Comment by bernardowilson** [comment]
I configured the library using either the gmp-ecc-128, gmp-pbc-128 or gmp-pbc-128 presets at compile time; I'm running the latest git master commit.

**Comment by conradoplg** [comment]
Does your code initialize the library (`core_init()`) and the elliptic curve (`ec_param_set_any()` or equivalent)?

**Comment by FiloSottile** [comment]
(FWIW, I was also tripped by missing initialization and took me quite a bit to find out that G was 0. Maybe a nice error message?)

**Comment by dfaranha** [comment]
Closed, problem most likely due to missing initialization.
