### ISSUE TITLE
relic does not work with windows, when i create vs project with cmake

### ISSUE THREAD

**Issue by juzix-kelvin** [relic-toolkit/relic#63]
i found that this library does not work with my win7 and Visual Studio development environment, a lot of compile error, and i cannot find the "dbl_t" definition.
Here are the output:
1>D:\workspace\git-work\MPC\WinTest\MPC\mpc-emp\relic\src\low\easy\relic_fp_sqr_low.c(94): error C2065: “dbl_t”: undelared symbol
1>D:\workspace\git-work\MPC\WinTest\MPC\mpc-emp\relic\src\low\easy\relic_fp_sqr_low.c(94): error C2065: “s”: undelared symbol
1>D:\workspace\git-work\MPC\WinTest\MPC\mpc-emp\relic\src\low\easy\relic_fp_sqr_low.c(97): error C2065: “dbl_t”: undelared symbol
1>D:\workspace\git-work\MPC\WinTest\MPC\mpc-emp\relic\src\low\easy\relic_fp_sqr_low.c(97): error C2146: syntax error

**Comment by conradoplg** [comment]
What exactly do you mean with "does not work"?

**Comment by juzix-kelvin** [comment]
Where can i find the "dbl_t", and have you guys test the relic on windows platform ?  waiting for help ~~

**Comment by juzix-kelvin** [comment]
I quit on the complination on win7 with visual studio2015, and switch to cygwin dev environment. For now everything seems smooth for me.

**Comment by conradoplg** [comment]
Sorry, we don't usually test other build systems. I remember testing on VS many years ago and got some issues because the VS C compiler had only C89 support, and had to change the project to compile as C++...

Anyway, glad you got it working. Someday I'll try to make it work on VS, but I think it's not a priority right now.

**Comment by dis2** [comment]
I highly suggest you use mingw for relic, and then use the resulting .a file in vs project.

msys/cygwin works fine too, but you wont be able to link such a library from MSVC.

**Comment by dfaranha** [comment]
While noting that #98 was recently merged, I consider this fixed.
