### ISSUE TITLE
Unexpected failure of ep2_mul[_lwnaf] above the prime group order

### ISSUE THREAD

**Issue by FiloSottile** [relic-toolkit/relic#64]
I have a point and I want to scale it by the cofactor. I get three different answers with three different methods.

## ep2_mul_basic

```
void ep2_scale_by_cofactor(ep2_t p) {
    bn_t k;
    bn_new(k);
    bn_read_str(k, "5d543a95414e7f1091d50792876a202cd91de4547085abaa68a205b2e5a7ddfa628f1cb4d9e82ef21537e293a6691ae1616ec6e786f0c70cf1c38e31c7238e5", 127, 16); // FROM RUST IMPLEMENTATION
    ep2_mul_basic(p, p, k);
    bn_free(k);
}
```

This matches the result of the ebfull/pairing Rust implementation when used with the cofactor lifted from there. 

https://github.com/ebfull/pairing/blob/a8583dd81840d1b970ff90905bfa582d67910e41/src/bls12_381/ec.rs#L1346-L1353

## ep2_mul

```
void ep2_scale_by_cofactor(ep2_t p) {
    bn_t k;
    bn_new(k);
    bn_read_str(k, "5d543a95414e7f1091d50792876a202cd91de4547085abaa68a205b2e5a7ddfa628f1cb4d9e82ef21537e293a6691ae1616ec6e786f0c70cf1c38e31c7238e5", 127, 16); // FROM RUST IMPLEMENTATION
    ep2_mul(p, p, k); // FOR SOME REASON ep2_mul[_lwnaf] returns a wrong result
    bn_free(k);
}
```

Using the default `ep2_mul` implementation returns a different result when used with the same cofactor value.

## ep2_mul_cof_b12

Using the *ahem* unexported `ep2_mul_cof_b12` from `ep2_map` returns a yet different result.

---

Full cmake:

```
cmake -DALLOC=DYNAMIC -DFP_PRIME=381 \
		-DSHLIB=off -DSTLIB=on -DRAND=UDEV -DTESTS=1 -DBENCH=0 \
		-DCOMP="-O3 -funroll-loops -Wno-unused-function"
```

**Comment by conradoplg** [comment]
From what I understand, `ep2_mul_lwnaf` calls `ep2_mul_glv_imp` which only works modulo the prime group order, so it can't be used to multiply by the cofactor. (Yep, needs better documentation... :sweat: )

As per `ep2_mul_cof_b12`, at a glance, I have no idea... @dfaranha, do you remember from where that formula comes from?

**Comment by FiloSottile** [comment]
I think it's not just a matter of documentation, if possible a error should be raised instead of returning a wrong value, and maybe `ep2_mul` shouldn't be a macro for a limited multiplication function.

**Comment by conradoplg** [comment]
Agreed, makes sense to raise an error.

I think the idea is that `ep2_mul` is guaranteed to work only on the prime-order subgroup. Again, needs better documentation...

**Comment by FiloSottile** [comment]
```
>>> x = -0xd201000000010000
>>> cofactor = (x**8 - 4*x**7 + 5*x**6 - 4*x**4 + 6*x**3 - 4*x**2 - 4*x + 13) / 9
>>> hex(cofactor)
'0x5d543a95414e7f1091d50792876a202cd91de4547085abaa68a205b2e5a7ddfa628f1cb4d9e82ef21537e293a6691ae1616ec6e786f0c70cf1c38e31c7238e5L'
```

The value I lifted from the code checks out with the formula (x<sup>8</sup> - 4x<sup>7</sup> + 5x<sup>6</sup> - 4x<sup>4</sup> + 6x<sup>3</sup> - 4x<sup>2</sup> - 4x + 13) / 9 from https://github.com/ebfull/pairing/blob/master/src/bls12_381/README.md.

The x variable corresponds with `fp_param_get_var`:

```
>>> x == -(2**63 + 2**62 + 2**60 + 2**57 + 2**48 + 2**16)
True
```

Now I'm trying to match this to the formula in `ep2_mul_cof_b12`, which AFAICT is:

(x<sup>2</sup> - x - 1)P + Ψ(x - 1)P + Ψ<sup>2</sup>(2P)

But that's where I am stuck.

**Comment by conradoplg** [comment]
The formula seems to match section 4.1 of https://eprint.iacr.org/2017/419.pdf , needs more investigation...

**Comment by conradoplg** [comment]
From a cursory reading, it does states that it multiplies the point by a multiple of the cofactor, which would explain the difference.

**Comment by dfaranha** [comment]
Exactly, the method of Fuentes et al. computes a compact expansion of a multiple of the cofactor using lattice reduction.

**Comment by FiloSottile** [comment]
Thanks, that explains `ep2_mul_cof_b12`, about which I can't complain anyway since it's unexported.

In FiloSottile/powersoftau#3 I verified the value of the coefficient, so I think the only issue left is about the unexpected failure of ep2_mul[_lwnaf].

**Comment by mogisawa** [comment]
Hello. (I hope my poor english make a sence ...)
First, about `ep2_mul_lwnaf`.
To raise error means to check the point is in sub-group. 
The check costs match. (check sub-group's order * P == O).
So raising error in each call of the function may be difficult for speed.
`ep2_mul` should be used in a situation of P is in the sub-group sure.
This situation is not special because once a point in sub-group, scalar-multiplication(or add, double, sub) makes a result in sub-group.

Second about the method of Fuentes et al.
In Section 3.1 of the pdf, it seems computing triple of [c(x)]P?
The pdf scopes mapping to the sub-group, so they don't consider about exact co-factor multiplication.
But it's maybe my misreading...

**Comment by mogisawa** [comment]
Forget about section 3.1.
I read a wrong section. The result is not triple of [c(x)]P.
Instead, "[h(a)]P is a multiple of [c]P" written in section 4.1 and eq.(12) computes [h(a)]P.
So the result of `ep2_mul_cof_b12` is as written.
However, in my test, the result is not equals [h(a)]P=[(3x^2-3)c(x)]P.
Hm...

**Comment by mogisawa** [comment]
Ah! In `ep2_curve_set_twist`, cofactor(h) is set to 1. (noted TODO...)
I used `ep2_curve_get_cof`...
Using concrete value(5d54... that FiloSottile said), the result satisfies above equation; [h(a)]P=[(3x^2-3)c(x)]P.
`ep2_mul_cof_b12` should rename `ep2_mul_multiple_cof` or etc., but no bugs is.

Use `ep2_mul_basic` with general point, including points that is not in sub-group,
use `ep2_mul` with points that in sub-group only,
and use `ep2_mul_cof_b12` with general points to mapping to sub-group, it does not cofactor multiplicate.
So, with points not in sub-group, these functions compute different result each.

**Comment by dfaranha** [comment]
Thanks again for the feedback!

The documentation of the `ep2` module now explicitly states this limitation of the `ep2_mul()` macro and general implementation.
I added `ep2_mul_big()` for the general case when the scalar is beyond the order and `ep2_mul_cof` for multiplication by the cofactor (or small multiples of it) in a way that the resulting point is in the large prime order subgroup.

Hope it is a bit more clear for future users.
