### ISSUE TITLE
Signature Aggregation

### ISSUE THREAD

**Issue by IlyaGazman** [relic-toolkit/relic#65]
Hi,

I am a developer with limited math knowledge, I would like to know, will it be possible to use this library to implement signature aggregation to combine n signatures generated from n distinct keys and messages into 1 compact signature that will not take more space then 1 of the n signatures.

Basically, I would like to know if using this library I can implement the signature aggregation idea as it described in [Aggregate and Verifiably Encrypted Signatures from Bilinear Maps](https://crypto.stanford.edu/~dabo/pubs/papers/aggreg.pdf)

**Comment by conradoplg** [comment]
Yes, it should be possible. You would need to write a new "protocol", see https://github.com/relic-toolkit/relic/blob/5784facac01fc27fd9960cb8a9065b0a60b140ff/src/cp/relic_cp_bls.c for an example with the BLS signature scheme (on which the scheme in the paper you cited is based).

**Comment by dfaranha** [comment]
And I just hope this won't end up in production of some cryptocurrency somewhere. :)

**Comment by IlyaGazman** [comment]
I am not sure that I am capable of writing a new protocol. I was hoping to see an example of how this could be achieved, also please tell me if this can be used in cryptocurrency production environment from a security point of view, this is my final goal after all :)

**Comment by dfaranha** [comment]
I have no idea if the protocol matches your objectives, but I must heavily advise against deploying RELIC in production. It's a research library, not really well-suited for production. Take a look at the ZCash for a more polished codebase implementing pairings.

**Comment by IlyaGazman** [comment]
As I mentioned earlier I am mostly a developer, my math skills are not high enough to construct the proper implementation as I need. At the moment I just want to see a working example so at least I will have an anchor to something that is working. After that I will be able to compare it with other libraries and build proper tests on top of it, to improve my confidence.

Also, my cryptocurrency is Java-based, so whatever example I will see here I am planning to translate to Java along with all of its dependencies.

**Comment by conradoplg** [comment]
You asked if aggregate signature can be implemented with RELIC. It can be. The BLS code *is* an example of how you can achieve what you want... you would need to copy it and change to implement the aggregate signature described in the paper. To help you more than that we'd need to actually implementing it for you :smile: 

But if you're asking if RELIC supports aggregate signature out of the box, than the answer is no, sorry.

**Comment by Ilya-Gazman** [comment]
Ok, 👍  can you please make it a feature request :)

**Comment by brianosaurus** [comment]
👍 +1

**Comment by dfaranha** [comment]
https://medium.com/@sergey_nog/how-not-to-use-aggregate-signatures-in-your-blockchain-63e05be2cbbe

**Comment by dfaranha** [comment]
Implemented in `relic_cp_bls.c`.
