### ISSUE TITLE
Unable to build on windows because of the FIXED constant

### ISSUE THREAD

**Issue by Scratch-net** [relic-toolkit/relic#67]
Windows has FIXED defined, so when trying to build Relic under windows (with mingw) it fails with 
- D:/go/src/gopkg.in/pythia.v0/pythia/lib/pythia/cmake-build-release/relic-prefix/src/relic-build/include/relic_conf.h:531:16: error: expected identifier or '(' before numeric constant

This is fixed in #45 . Could you please port that part of fix?

**Comment by codablock** [comment]
This should be fixed with https://github.com/relic-toolkit/relic/pull/86
