### ISSUE TITLE
win64 microsoft calling convention for assembly

### ISSUE THREAD

**Issue by dis2** [relic-toolkit/relic#68]
As far I can't tell, it's not possible to convince mingw to call the asm routines with SYSV. Thus one having to fall back to gmp or easy for field arithmetic (in  case of EC).

Would something to the effect of:

```c
#ifndef __MINGW64__
// Everyone else
#define RDI %rdi
#define RSI %rsi
#define RDX %rdx
#define RCX %rcx
#define R8 %r8
#define R9 %r9
#define WINPUSH
#define WINPOP
#else
// Microsoft
#define RDI %rcx
#define RSI %rdx
#define RDX %r8
#define RCX %r9
#define R8 %rax // Make sure rax isn't used
#define R9 %rdi
#define WINPUSH push %rdi
#define WINPOP pop %rdi
#endif
```
Make sense, or would it be simpler to just stick SYSV->MS register shuffle in front of each asm \_low. Slight overhead, but far less invasive than making all the registers conditional. Of course if somebody knows how to convince mingw to talk to both worlds via some attribute, that would be nice, but never found a such a thing on my own.

**Comment by dfaranha** [comment]
Hi, did you make any progress on this in the past few years? :)

I have finally included MINGW builds as part of GH Actions and feel in better shape of trying to convert the ASM to its calling conventions.

**Comment by dfaranha** [comment]
Closed due to inactivity. We do not plan a rewrite of the ASM backends just for Windows support.
