### ISSUE TITLE
Missing fp6_mul_dxs_unr when STRIP=on is used together with PP_EXT == LAZYR

### ISSUE THREAD

**Issue by Scratch-net** [relic-toolkit/relic#69]
I use preset
- x64-pbc-128-b12.sh

```bash
-DWORD=64 -DRAND=UDEV -DSHLIB=OFF -DSTBIN=ON -DTIMER=CYCLE -DCHECK=off -DVERBS=off -DARITH=x64-asm-382 -DFP_PRIME=381 -DFP_METHD="INTEG;INTEG;INTEG;MONTY;LOWER;SLIDE" -DCOMP="-O3 -funroll-loops -fomit-frame-pointer -finline-small-functions -march=native -mtune=native" -DFP_PMERS=off -DFP_QNRES=on -DFPX_METHD="INTEG;INTEG;LAZYR" -DEP_PLAIN=off -DEP_SUPER=off -DPP_METHD="LAZYR;OATEP"
```

if I add STRIP=on to it then I get

```
./lib/librelic_s.a(relic_fp18_mul.c.o): In function `fp18_mul_dxs_lazyr':

relic_fp18_mul.c:(.text+0xed0): undefined reference to `fp6_mul_dxs_unr'

relic_fp18_mul.c:(.text+0xeee): undefined reference to `fp6_mul_dxs_unr'
```

Looks like fp6_mul_dxs_unr should be moved under 
```c
#if PP_EXT == LAZYR || !defined(STRIP)
```
and not

```c
#if PP_EXT == BASIC || !defined(STRIP)
```

which fixes the problem.

Should I make a PR?

**Comment by dfaranha** [comment]
Yes, please, thanks! :)
--
Diego de Freitas Aranha
Institute of Computing - University of Campinas
http://www.ic.unicamp.br/~dfaranha

**Comment by Scratch-net** [comment]
Thanks. Created #70

**Comment by Scratch-net** [comment]
Thanks, everything works now, the library is about ~870kb.
Maybe you have an idea of how we can minify it even more? We are planning to use it in web browsers where megabyte-sized libraries are tough to explain
