### ISSUE TITLE
if the relic library will remove the gmp library dependency, just to make it a pure crypto library ?

### ISSUE THREAD

**Issue by juzix-kelvin** [relic-toolkit/relic#71]
I wonder if the library will be a pure crypto library,  because in some circumstance, we need to transform to chrome or windows platform, will pure crypto library it will be much more easy. But now the gmp library is some kind of limitation.  How to remove gmp from the library,  I am not sure how much works it will take ! Any advice to offer will be gratefull,  help !!!

**Comment by conradoplg** [comment]
Just use the "easy" backend (`cmake -DARITH=easy .`)

**Comment by juzix-kelvin** [comment]
thank u, i have fixed it  :)

--------------原始邮件--------------
发件人："Conrado Porto Lopes Gouvêa "<notifications@github.com>;
发送时间：2018年3月23日(星期五) 晚上7:57
收件人："relic-toolkit/relic" <relic@noreply.github.com>;
抄送："juzix-kelvin "<huanggaofeng@juzix.io>;"Author "<author@noreply.github.com>;
主题：Re: [relic-toolkit/relic] if the relic library will remove the gmplibrary dependency, just to make it a pure crypto library ? (#71)
-----------------------------------

Just use the "easy" backend (cmake -DARITH=easy .)
