### ISSUE TITLE
undefined reference to `ed_mul_fix_lwnaf_mixed'

### ISSUE THREAD

**Issue by conradoplg** [relic-toolkit/relic#74]
When running the commented out test in `.travis.yml`, the build fails with `undefined reference to `ed_mul_fix_lwnaf_mixed'`. I couldn't find this function defined anywhere in the library.

**Comment by dfaranha** [comment]
It's probably a leftover artifact from the previous refactoring inside the ED module. I suggest removing it from the include files and the symbol LWNAF_MIXED from the configuration.

**Comment by dfaranha** [comment]
References to LWNAF_MIXED are now removed from the codebase. Performance of the ED module can certainly be improved with mixed coordinates, which I assume was the intention of the initial function. I will open a new ticket instead.
