### ISSUE TITLE
Infinite loop in fp_inv_monty when 0 is passed

### ISSUE THREAD

**Issue by Scratch-net** [relic-toolkit/relic#76]
This leads to infinite loops when deserializing GT, looks like a critical bug

**Comment by Scratch-net** [comment]
Same happens when FP_INV is BINAR

**Comment by dfaranha** [comment]
This should have been fixed in d98b7bda093468abadababdc9c72c5415a6257b6

Can you please check?

**Comment by Scratch-net** [comment]
Sorry, it was more than a year ago, we already added a workaround for it.  I believe in your expertise )
