### ISSUE TITLE
Const in fp2

### ISSUE THREAD

**Issue by mariano54** [relic-toolkit/relic#79]
Hello, I was wondering if there is a reason why const is not used in fp2/fpx/ep2, while it is used for fp?

I noticed this while trying to compare two const g2 points (ep2_cmp).

Thanks!

**Comment by alinush** [comment]
Yes, lots of functions that should take const variables do not. I was wondering the same thing...

**Comment by dfaranha** [comment]
I tried to do const-correctness across the whole code base and ended up needed lots of casts for the more complex types, especially to support the multiple memory allocators. With this getting simplified (ALLOC=STATIC is dead), it should be easier to solve.

**Comment by alinush** [comment]
I am in the process of adding const correctness in. What build flags should I test with to make sure I don't break anything? I'll submit a pull request.

**Comment by dfaranha** [comment]
The default ones and also ALLOC=DYNAMIC or STACK for a start.

**Comment by dfaranha** [comment]
This was actually solved a while ago.
