### ISSUE TITLE
Question about BN-381 curve

### ISSUE THREAD

**Issue by NickyYangYang** [relic-toolkit/relic#80]
Hi,
    Your BN-381 curve  use  param  -(2^94 + 2^78 + 2^67 + 2^64 + 2^48 + 1). Why not use the BN curve in Family of Implementation-Friendly BN Elliptic Curves, which param is -(2^94 + 2^76 + 2^72 + 1).
    Are both BN-381 curve secure?

**Comment by dfaranha** [comment]
Hi,

I have used a curve provided by Barreto himself on a Twitter thread: https://twitter.com/grittygrease/status/829037821792903168

This curve should be better in terms of subgroup security (https://eprint.iacr.org/2015/247.pdf) in comparison to the one in the family paper, but this type of attacks may or not applicable to your protocol.
