### ISSUE TITLE
Question about EC point addition function in RELIC library

### ISSUE THREAD

**Issue by carlweng** [relic-toolkit/relic#89]
Hi everyone,

I'm using RELIC library to run algorithms on elliptic curve, but I get confused by the point addition function **ec_add(R, P, Q)**, which means R = P + Q.

My test code is like:

```
ec_t a, b, c;

ec_null(a);
ec_null(b);
ec_null(c);
ec_new(a);
ec_new(b);
ec_new(c);

ec_rand(b);
ec_rand(c);
ec_set_infty(a);

ec_add(a, b, c);
```

This is just like the code in file "relic/test_ec.c"
But using ec_print() function, I get wired results:

```
a
0000000000000000 0000000000000000 0000000000000000 0000000000000000
0000000000000000 0000000000000000 0000000000000000 0000000000000000
0000000000000000 0000000000000000 0000000000000000 0000000000000000
b
05BE77ECC02A6481 AF4B66D638E6986A B4302B1A4F11BC56 FB3D0F7A4B3F2001
01D6494E522921D3 1165DDB1A0F9E6DE 9B3DAD4A5200B6B3 C5E2D4CE61B807B9
0000000000000000 0000000000000000 0000000000000000 0000000000000001
c
06CAA1B1B56B6730 0745EE53A74EB8C6 6931896B2915900D 05F48503CC38CA74
0470A4671E10BEEF 09025C96E2AE83CA 8163488B1F66EC19 35360247BF2841AC
0000000000000000 0000000000000000 0000000000000000 0000000000000001
a=b+c
02D2DB5A26E77D83 B1544C8293B5BA70 5325DB54B0E1A796 71A4815F605F9DB3
05CD66BDB946740C 137C19686642DE73 49EF6D95DE06B474 1314599FE5824BF9
00020F9085B924D2 0D9E12B058802703 7D519C6DECED295E 3ED3285FD0A31784
```

It's true that b + c and c + b would get the same result, but I don't think it is the right answer. Could you figure out what's wrong with my code or is there anything wrong with the library.

**Comment by dfaranha** [comment]
You need to convert points to affine coordinates using ec_norm() before you can compare them.

**Comment by carlweng** [comment]
> You need to convert points to affine coordinates using ec_norm() before you can compare them.

Oh, I didn't notice that. Thank you for your reply.
Seems that I need to know more about elliptic curves. So curious about how to convert points to affine coordinates and how it doesn't effect the correctness of the point arithmetic.

**Comment by dfaranha** [comment]
We got this question many times already, so we should think of converting them to affine before printing (and perhaps have another function for "raw" printing for debugging purposes).

Good luck!
